import Link from "next/link";
import { PageHeading } from "@/components/page-heading";
import { TestingNavigation } from "@/components/testing-navigation";
import { loadCoachingData } from "@/lib/analytics-server";
import { coachUpdateDigest } from "@/lib/coach-update-digest";
import { coachingValue } from "@/lib/coaching-tools";
import { pacificTestingDate } from "@/lib/testing-checklist";

const pretty=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`));
export default async function ChangesPage(){
  // loadCoachingData performs a fresh staff authorization check before team reads.
  const digest=coachUpdateDigest(await loadCoachingData(),pacificTestingDate());
  return <><PageHeading section="Pacific Baseball / Staff Tools" title="What Changed" description={`Newly saved results since ${pretty(digest.since)}. Comparisons use a prior distinct test date in the same metric, unit and source.`}><Link href="/testing/coverage" className="btn btn-secondary">Data Coverage</Link></PageHeading><TestingNavigation changes/>
    <div className="grid gap-3 sm:grid-cols-3"><div className="card p-5"><p className="muted m-0 text-xs font-bold uppercase tracking-wider">Saved Readings · 7 Days</p><strong className="mt-2 block text-3xl font-black tabular-nums">{digest.recentReadings}</strong></div><div className="card p-5"><p className="muted m-0 text-xs font-bold uppercase tracking-wider">Players Updated</p><strong className="mt-2 block text-3xl font-black tabular-nums">{digest.updatedPlayers.length}</strong></div><div className="card p-5"><p className="muted m-0 text-xs font-bold uppercase tracking-wider">No Recent Test · 21 Days</p><strong className="mt-2 block text-3xl font-black tabular-nums">{digest.stale.length}</strong></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="card p-5 sm:p-6"><h2 className="m-0 text-xl font-bold">New Results</h2><p className="muted mb-3 mt-1 text-sm">Most recent players with saved Fall testing in the past seven days.</p>{digest.updatedPlayers.length?<ul className="m-0 list-none divide-y divide-[var(--line-subtle)] p-0">{digest.updatedPlayers.slice(0,15).map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><Link className="font-bold text-[var(--accent-readable)]" href={`/athletes/${item.id}`}>{item.name}</Link><p className="muted m-0 mt-1 text-xs">{item.areas.join(" · ")} · {item.readings} {item.readings===1?"reading":"readings"}</p></div><time className="text-xs text-[var(--text-secondary)]" dateTime={item.lastDate}>{pretty(item.lastDate)}</time></li>)}</ul>:<p className="muted text-sm">No new testing saved in this window.</p>}</section>
      <section className="card p-5 sm:p-6"><h2 className="m-0 text-xl font-bold">Measured Changes</h2><p className="muted mb-3 mt-1 text-sm">At least 5% from a prior distinct test. This is a display threshold, not a performance or health grade.</p>{digest.changes.length?<ul className="m-0 list-none divide-y divide-[var(--line-subtle)] p-0">{digest.changes.slice(0,15).map((item,index)=><li key={`${item.playerId}:${item.metric}:${item.source}:${index}`} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><Link href={`/athletes/${item.playerId}`} className="font-bold text-[var(--accent-readable)]">{item.playerName}</Link><span className="rounded-full bg-[var(--surface-raised)] px-2 py-1 text-xs font-bold tabular-nums">{item.percent>0?"+":""}{item.percent.toFixed(1)}%</span></div><p className="muted m-0 mt-1 text-xs">{item.label}: {coachingValue(item.previous,item.metric,item.unit,item.source)} → {coachingValue(item.value,item.metric,item.unit,item.source)} · {pretty(item.date)}</p></li>)}</ul>:<p className="muted text-sm">No comparable changes above this display threshold yet.</p>}</section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="card p-5 sm:p-6"><h2 className="m-0 text-xl font-bold">Testing Follow-Up</h2><p className="muted mb-3 mt-1 text-sm">Players with no saved Fall testing in the past 21 days. This is a recency view, not a due date.</p>{digest.stale.length?<ul className="m-0 list-none divide-y divide-[var(--line-subtle)] p-0">{digest.stale.slice(0,15).map(item=><li key={item.id} className="flex flex-wrap justify-between gap-2 py-2 text-sm"><Link href={`/athletes/${item.id}`} className="font-semibold text-[var(--accent-readable)]">{item.name}</Link><span className="text-xs text-[var(--text-secondary)]">{item.lastDate?`Last tested ${pretty(item.lastDate)}`:"No Fall test"}</span></li>)}</ul>:<p className="muted text-sm">Every rostered player has a recent saved Fall test.</p>}<Link href="/testing/coverage" className="mt-4 inline-block text-sm font-bold text-[var(--accent-readable)]">Open full coverage →</Link></section>
      <section className="card p-5 sm:p-6"><h2 className="m-0 text-xl font-bold">Game Sheet Status</h2><p className="muted mb-3 mt-1 text-sm">Current verified Fall snapshots. A new source save is not treated as a dated game or a player improvement.</p>{digest.games.map(game=><div key={game.source} className="flex flex-wrap justify-between gap-2 border-b border-[var(--line-subtle)] py-3 text-sm"><strong>{game.source==="qpa_fall_2026"?"QPA Hitting":"Pitching Stats"}</strong><span className="text-[var(--text-secondary)]">{game.players} players · {game.lastSynced?`Synced ${new Date(game.lastSynced).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}`:"Awaiting verified results"}</span></div>)}<Link href="/game-stats/review" className="mt-4 inline-block text-sm font-bold text-[var(--accent-readable)]">Open game data review →</Link></section></div>
    <p className="muted mt-5 text-xs">Saved testing reflects approved reports only. Sample sizes and source details remain on each player profile; repeated same-day trials are not presented as a before/after change.</p>
  </>;
}
