import { requireAccess } from "@/lib/auth";
import { PageHeading } from "@/components/page-heading";
import { SubmitButton } from "@/components/submit-button";
import { athleteName, type Athlete } from "@/lib/types";
import { configureAccount } from "./actions";
type Account = { user_id: string; is_active: boolean; account_roles: { role: string }[]; account_athletes: { athlete_id: string } | { athlete_id: string }[] | null };
export default async function AccessPage({ searchParams }: { searchParams: Promise<{error?:string;saved?:string}> }) {
  const { supabase, user } = await requireAccess(["admin"]);
  const params = await searchParams;
  const [accounts, athleteResult] = await Promise.all([supabase.from("app_accounts").select("user_id,is_active,account_roles(role),account_athletes(athlete_id)").order("created_at"),supabase.from("athletes").select("id,athlete_code,first_name,preferred_name,last_name").order("last_name").limit(1000)]);
  if (accounts.error || athleteResult.error) throw new Error("Unable to load account access.");
  const athletes = (athleteResult.data ?? []) as Athlete[];
  return <><PageHeading section="Administration" title="Account access" description="Configure access for an existing Auth user. Select the exact user ID and verify the athlete identity." />
    {params.error && <p role="alert" className="notice notice-error mb-6">{params.error === "input" ? "Enter a valid Auth user ID, choose roles, and confirm the change." : "Access was not changed. Confirm that the Auth user exists, the athlete is not linked elsewhere, and you are not changing your own account."}</p>}
    {params.saved && <p role="status" className="notice notice-success mb-6">Account access saved and audited.</p>}
    <section className="panel mb-7 p-7"><h2 className="mb-2 text-lg font-semibold">Approve account access</h2><p className="muted mb-6 text-sm">This replaces the selected account’s roles, status, and athlete link. An empty athlete selection removes its link. Account creation happens separately in Supabase.</p><form action={configureAccount} className="space-y-5"><label>Existing Supabase Auth user ID<input name="user_id" placeholder="Paste the exact UUID from Supabase → Authentication → Users" required /></label><fieldset><legend className="mb-2 text-sm font-semibold">Roles</legend><div className="flex flex-wrap gap-6">{["admin","coach","player"].map(role => <label className="flex items-center gap-2 capitalize" key={role}><input type="checkbox" name="roles" value={role} />{role}</label>)}</div></fieldset><label>Linked athlete (requires Player role)<select name="athlete_id" defaultValue=""><option value="">No athlete link</option>{athletes.map(a => <option key={a.id} value={a.id}>{a.athlete_code} · {athleteName(a)}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" name="active" value="yes" />Account is active</label><label className="flex items-start gap-3 rounded-md bg-gray-50 p-4"><input type="checkbox" name="confirm" value="yes" required /><span>I verified the Auth user ID, roles, active status, and athlete link, and approve this change.</span></label><SubmitButton pendingText="Saving access…">Save approved access</SubmitButton></form><p className="muted mb-0 mt-5 text-xs">Your own account ({user.id}) must be changed by another administrator or the owner using the documented SQL procedure.</p></section>
    <h2 className="mb-4 text-lg font-semibold">Configured accounts</h2><div className="panel table-wrap"><table><thead><tr><th>Auth user ID</th><th>Roles</th><th>Status</th><th>Linked athlete</th></tr></thead><tbody>{(accounts.data as Account[]).map(a => { const link = Array.isArray(a.account_athletes) ? a.account_athletes[0] : a.account_athletes; const athlete = athletes.find(x => x.id === link?.athlete_id); return <tr key={a.user_id}><td className="font-mono text-xs">{a.user_id}</td><td className="capitalize">{a.account_roles.map(r=>r.role).join(" + ")}</td><td><span className={`badge ${a.is_active ? "badge-green" : "badge-red"}`}>{a.is_active ? "Active" : "Disabled"}</span></td><td>{athlete ? `${athlete.athlete_code} · ${athleteName(athlete)}` : "—"}</td></tr>; })}</tbody></table></div>
  </>;
}
