import { describe, expect, it } from "vitest";
import { analyticsVariables, latestAnalyticsReadings, linearFit, pairAnalytics, readingsForPeriod, variableKey, pointGroup, type AnalyticsPlayer, type AnalyticsReading } from "@/lib/analytics";
const player=(id:string):AnalyticsPlayer=>({id,code:`SYN-${id}`,name:`Fictional Player ${id}`,academicClass:"freshman",position:"OF",playerType:"position",bats:"R",throws:"R"});
const row=(overrides:Partial<AnalyticsReading>={}):AnalyticsReading=>({id:"obs-1",athleteId:"1",metric:"weight",label:"Weight",unit:"lb",source:"Fictional Scale",date:"2026-09-06",value:180,importedAt:"2026-09-06T20:00:00Z",...overrides});
describe("analytics measurement pairing",()=>{
 it("keeps sources, units, and metrics separate and only counts each player once",()=>{const readings=[row(),row({id:"2",value:181,date:"2026-09-07"}),row({id:"3",unit:"kg",value:80}),row({id:"4",source:"Different Device"})];expect(analyticsVariables(readings).map(v=>v.count)).toEqual([1,1,1]);expect(latestAnalyticsReadings(readings).find(r=>r.unit==="lb"&&r.source==="Fictional Scale")?.value).toBe(181);});
 it("uses deterministic latest date, import time and observation ID",()=>{const readings=[row({id:"a"}),row({id:"b",value:182}),row({id:"c",value:184,date:"2026-09-05",importedAt:"2026-09-09T00:00:00Z"})];expect(latestAnalyticsReadings(readings)[0].value).toBe(182);expect(latestAnalyticsReadings(readings.toReversed())[0].value).toBe(182);});
 it("pairs by permanent player ID, excludes missing readings and honors exact gap boundaries",()=>{const x=row(),y=row({id:"y",metric:"muscle_mass",value:140,date:"2026-09-13"}),other=row({id:"other",athleteId:"2"});let r=pairAnalytics([player("1"),player("2"),player("3")],[x,y,other],variableKey(x),variableKey(y),7);expect(r.points).toHaveLength(1);expect(r.points[0].gap).toBe(7);expect(r.excluded.map(e=>e.reason)).toEqual(["Missing Y measurement","Missing both measurements"]);r=pairAnalytics([player("1")],[x,y],variableKey(x),variableKey(y),6);expect(r.points).toHaveLength(0);expect(r.excluded[0].reason).toContain("7 days");});
 it("does not reach back to an older test to force a pair",()=>{const a=row(),old=row({id:"old",date:"2026-09-01"}),y=row({id:"y",metric:"height",date:"2026-09-01"});expect(pairAnalytics([player("1")],[a,old,y],variableKey(a),variableKey(y),0).points).toHaveLength(0);});
 it("separates Fall from June–August body results and excludes earlier baseball",()=>{const readings=[row(),row({date:"2026-08-01"}),row({metric:"max_bat_speed",date:"2026-08-01"})];expect(readingsForPeriod(readings,"fall")).toHaveLength(1);expect(readingsForPeriod(readings,"earlier")).toHaveLength(1);});
 it("retains zero as a measurement and exposes unknown groups explicitly",()=>{expect(pairAnalytics([player("1")],[row({value:0}),row({id:"h",metric:"height",value:70})],variableKey(row()),variableKey(row({metric:"height"})),0).points[0].x.value).toBe(0);expect(pointGroup({...player("1"),academicClass:""},"academicClass")).toBe("Not Listed");});
});
describe("Pearson correlation and least-squares fit",()=>{
 it("fits known positive and negative lines",()=>{for(const slope of [2,-3]){const fit=linearFit([1,2,3,4,5].map(x=>({x,y:slope*x+7})))!;expect(fit.slope).toBeCloseTo(slope,12);expect(fit.r).toBeCloseTo(Math.sign(slope),12);expect(fit.rSquared).toBeCloseTo(1,12);expect(fit.meanY-fit.slope*fit.meanX).toBeCloseTo(7,12);}});
 it("does not mistake a curved symmetric relationship for linear correlation",()=>{const fit=linearFit([-2,-1,0,1,2].map(x=>({x,y:x*x})))!;expect(fit.r).toBeCloseTo(0,12);expect(fit.slope).toBeCloseTo(0,12);});
 it("handles small samples, constant axes, and nonfinite data honestly",()=>{expect(linearFit([{x:1,y:2},{x:2,y:4}])).toBeNull();expect(linearFit(Array.from({length:7},(_,i)=>({x:.6,y:i})))).toBeNull();const fit=linearFit(Array.from({length:7},(_,i)=>({x:i,y:.6})))!;expect(fit.r).toBeNull();expect(fit.rSquared).toBeNull();expect(fit.slope).toBe(0);expect(linearFit([1,2,3,4,5].map(x=>({x,y:Infinity})))).toBeNull();});
 it("is invariant to units for r, and scales the line appropriately",()=>{const points=[{x:1,y:1},{x:2,y:2},{x:3,y:4},{x:4,y:3},{x:5,y:6}],a=linearFit(points)!,b=linearFit(points.map(p=>({x:p.x*1000,y:p.y/10})))!;expect(a.r).toBeCloseTo(b.r!,12);expect(a.slope/10000).toBeCloseTo(b.slope,12);});
});
