import { describe, expect, it } from "vitest";
import { battingRates, formatBattingRate } from "@/lib/batting-stats";
import { qpaAnalytics } from "@/lib/game-analytics";
import type { SharedGameStat } from "@/lib/game-server";
const rows=(values:Record<string,number>):SharedGameStat[]=>Object.entries(values).map(([metric,value])=>({source:"qpa_fall_2026",athlete_id:"fictional-player",metric,value,unit:"count",scope:"cumulative_fall",event_id:null,played_on:null,source_row:2,source_column:2,derived_from:[],snapshot_id:"fictional-snapshot",fetched_at:"2026-09-13T01:00:00Z",content_hash:"a".repeat(64)}));
describe("confirmed QPA batting definitions",()=>{
 it("uses all-hit total once without adding overlapping hard hits or home runs",()=>{const result=battingRates(rows({pa:12,ab:10,base_hit:3,hh_base_hit:2,hh_extra_base_hit:1,pumps:1,bb:2,punchies:4}));expect(result.find(r=>r.metric==="batting_avg")?.value).toBe(.3);expect(result.find(r=>r.metric==="batting_bb_pct")?.value).toBeCloseTo(100/6);expect(result.find(r=>r.metric==="batting_k_pct")?.value).toBeCloseTo(100/3);expect(result.map(r=>r.label)).toEqual(["AVG","BB %","K %"]);});
 it("retains confirmed zeros but never fills missing numerators or zero denominators",()=>{expect(battingRates(rows({ab:5,base_hit:0}))[0].value).toBe(0);expect(battingRates(rows({ab:5}))).toEqual([]);expect(battingRates(rows({ab:0,base_hit:0}))).toEqual([]);expect(battingRates(rows({ab:5,base_hit:6}))).toEqual([]);});
 it("rejects mixed players, snapshots, duplicate metrics and invalid values",()=>{const base=rows({ab:10,base_hit:3});for(const extra of [{...base[0],athlete_id:"other"},{...base[0],snapshot_id:"other"},base[0],{...base[0],value:NaN}])expect(battingRates([...base,extra])).toEqual([]);});
 it("calculates OBP only with recorded sacrifice flies, excluding sacrifice bunts",()=>{const values={ab:10,base_hit:3,bb:2,hbp:1,sac_fly:1,sac_bunt:2};expect(battingRates(rows(values)).find(r=>r.metric==="batting_obp")?.value).toBe(6/14);expect(battingRates(rows({...values,sac_fly:0})).find(r=>r.metric==="batting_obp")?.value).toBe(6/13);const {sac_fly,...missing}=values;expect(sac_fly).toBe(1);expect(battingRates(rows(missing)).some(r=>r.metric==="batting_obp")).toBe(false);});
 it("withholds OBP when PA is smaller than AB plus walks, HBP and sacrifice flies",()=>{expect(battingRates(rows({pa:5,ab:5,base_hit:2,bb:0,hbp:0,sac_fly:1})).some(r=>r.metric==="batting_obp")).toBe(false);});
 it("uses the exact QPA HH formula and rejects impossible or undefined rates",()=>{const values={hh_base_hit:2,three_eight_hh:1,hh_extra_base_hit:1,pumps:1,ab:12,punchies:1,sac_bunt:1};expect(battingRates(rows(values)).find(r=>r.metric==="batting_hh_pct")?.value).toBe(50);expect(battingRates(rows({...values,ab:2})).some(r=>r.metric==="batting_hh_pct")).toBe(false);});
 it("keeps Analytics limited to the eight requested game variables",()=>{const output=qpaAnalytics(rows({pa:12,ab:10,base_hit:3,bb:1,punchies:1,hbp:0,sac_fly:1,gdp:0,pumps:1,sb:1,qpa_pct:50,hh_base_hit:1,three_eight_hh:0,hh_extra_base_hit:0,sac_bunt:0,rbi:2}));expect(output.map(r=>r.metric).sort()).toEqual(["batting_avg","batting_bb_pct","batting_k_pct","batting_hh_pct","qpa_game_gdp","qpa_game_pumps","qpa_game_sb","qpa_game_qpa_pct"].sort());});
 it("formats baseball averages and percentage rates distinctly",()=>{expect(formatBattingRate({metric:"x",label:"x",value:1/3,unit:"avg"})).toBe(".333");expect(formatBattingRate({metric:"x",label:"x",value:1,unit:"avg"})).toBe("1.000");expect(formatBattingRate({metric:"x",label:"x",value:12.34,unit:"%"})).toBe("12.3%");});
 it("dates cumulative analytics by Pacific snapshot day without inventing games",()=>{const result=qpaAnalytics(rows({pa:12,ab:10,base_hit:3,pumps:1}));expect(result.find(r=>r.metric==="batting_avg")?.value).toBe(.3);expect(result.every(r=>r.date==="2026-09-12"&&r.source.includes("snapshot date"))).toBe(true);expect(new Set(result.map(r=>r.id)).size).toBe(result.length);expect(qpaAnalytics([...rows({ab:10}),{...rows({base_hit:3})[0],snapshot_id:"other"}])).toEqual([]);});
});
