import { beforeEach,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));
const fake=vi.hoisted(()=>({staffAccess:vi.fn(),access:vi.fn(),rpc:vi.fn(),revalidate:vi.fn()}));
vi.mock("@/lib/auth",()=>({requireImportAccess:fake.staffAccess,requireAccess:fake.access}));vi.mock("next/cache",()=>({revalidatePath:fake.revalidate}));
import { saveDevelopmentPlan,completeDevelopmentDrill } from "@/app/(workspace)/athletes/[id]/development-actions";
import { DEVELOPMENT_INITIAL_STATE } from "@/lib/development-plans";
const athlete="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",plan="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",request="dddddddd-dddd-4ddd-8ddd-dddddddddddd",drill="cccccccc-cccc-4ccc-8ccc-cccccccccccc";
function form(change:Record<string,string>={}){const data=new FormData();for(const [key,value] of Object.entries({athleteId:athlete,planId:plan,requestId:request,revision:"0",weekStart:"2026-09-28",focus:"Fictional plan",staffNote:"Fictional note",drills:JSON.stringify([{id:drill,title:"Fictional drill",cue:null}]),...change}))data.set(key,value);return data;}
beforeEach(()=>{vi.resetAllMocks();fake.staffAccess.mockResolvedValue({roles:["coach"],preview:null,athleteId:null,supabase:{rpc:fake.rpc}});fake.access.mockResolvedValue({roles:["player"],preview:null,athleteId:athlete,supabase:{rpc:fake.rpc}});fake.rpc.mockResolvedValue({data:{id:plan,revision:1},error:null});});
it("reauthorizes staff and saves a whitelisted explicit plan without automatic sharing",async()=>{expect(await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form())).toMatchObject({status:"saved"});expect(fake.staffAccess).toHaveBeenCalledOnce();expect(fake.rpc).toHaveBeenCalledExactlyOnceWith("staff_save_development_plan",expect.objectContaining({p_athlete_id:athlete,p_plan_id:plan,p_request_id:request,p_expected_revision:0,p_shared:false,p_archived:false,p_drills:[{id:drill,title:"Fictional drill",cue:null}]}));expect(fake.revalidate).toHaveBeenCalledWith(`/athletes/${athlete}`);});
it("blocks actual Players and Player View even with an underlying Admin account",async()=>{fake.staffAccess.mockResolvedValue({roles:["player"],actualRoles:["admin"],preview:{role:"player"},athleteId:athlete,supabase:{rpc:fake.rpc}});expect(await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form())).toMatchObject({status:"error"});expect(fake.rpc).not.toHaveBeenCalled();});
it("never accepts client-forged drill completions through staff save",async()=>{await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form({drills:JSON.stringify([{id:drill,title:"Fictional drill",cue:null,completedAt:"2026-09-30T00:00:00Z",secret:"extra"}])}));expect(fake.rpc).toHaveBeenCalledWith("staff_save_development_plan",expect.objectContaining({p_drills:[{id:drill,title:"Fictional drill",cue:null}]}));});
it.each<Record<string,string>>([{weekStart:"2026-09-29"},{focus:""},{drills:"["},{revision:"1.2"},{requestId:"bad"}])("rejects invalid input %# before any save",async change=>{expect(await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form(change))).toMatchObject({status:"invalid"});expect(fake.rpc).not.toHaveBeenCalled();});
it("returns stale and uncertain states without retrying or claiming success",async()=>{fake.rpc.mockResolvedValueOnce({data:null,error:{code:"40001"}});expect(await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form())).toMatchObject({status:"stale"});fake.rpc.mockResolvedValueOnce({data:{id:plan,revision:20},error:null});expect(await saveDevelopmentPlan(DEVELOPMENT_INITIAL_STATE,form())).toMatchObject({status:"unverified"});expect(fake.rpc).toHaveBeenCalledTimes(2);expect(fake.revalidate).not.toHaveBeenCalled();});
it("allows fresh own-player drill completion with the exact revision and request",async()=>{fake.rpc.mockResolvedValue({data:{id:plan,revision:2},error:null});expect(await completeDevelopmentDrill(DEVELOPMENT_INITIAL_STATE,form({revision:"1",drillId:drill,completed:"true"}))).toMatchObject({status:"saved"});expect(fake.access).toHaveBeenCalledOnce();expect(fake.rpc).toHaveBeenCalledExactlyOnceWith("complete_my_development_drill",{p_athlete_id:athlete,p_plan_id:plan,p_request_id:request,p_expected_revision:1,p_drill_id:drill,p_completed:true});});
it.each([{roles:["player"],preview:{role:"player"},athleteId:athlete},{roles:["player"],preview:null,athleteId:plan},{roles:["coach"],preview:null,athleteId:athlete}])("blocks preview, peer or staff completion %#",async access=>{fake.access.mockResolvedValue({...access,supabase:{rpc:fake.rpc}});expect(await completeDevelopmentDrill(DEVELOPMENT_INITIAL_STATE,form({revision:"1",drillId:drill,completed:"true"}))).toMatchObject({status:"error"});expect(fake.rpc).not.toHaveBeenCalled();});
it("does not turn an unauthenticated request into a save",async()=>{fake.access.mockRejectedValue(new Error("access denied"));await expect(completeDevelopmentDrill(DEVELOPMENT_INITIAL_STATE,form())).rejects.toThrow("access denied");expect(fake.rpc).not.toHaveBeenCalled();});
