import { expect, it, vi } from "vitest";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PDFDocument, PDFPage } from "pdf-lib";
vi.mock("server-only",()=>({}));
import { createExitMeetingPdf } from "@/lib/exit-meeting-pdf";
import type { ExitMeetingReport, ExitMeetingRow } from "@/lib/exit-meeting";

// Synthetic export used for visual QA; no actual player data or source report.
const metric=(label:string,value:string,percentile:number|null=80):ExitMeetingRow=>({label,value,source:"Fictional Full Swing · Intrasquad",date:"2026-09-16",basis:"Latest saved result",percentile,peers:percentile===null?null:12,sample:"28 readings"});
const report:ExitMeetingReport={name:"Fictional Boxer",code:"PAC-9999",jersey:"#0",position:"SS / P",academicClass:"Senior",batsThrows:"Bats R / Throws R",season:"Fall 2026",generatedAt:"2026-09-27T12:00:00Z",lastTested:"2026-09-16",lastGameUpdate:"2026-09-20T04:00:00Z",strengths:[{label:"Max Exit Velocity",detail:"105.2 mph · Full Swing Intrasquad · 2026-09-16 · 12 teammates",percentile:92},{label:"AVG · Hitting",detail:".350 · QPA Fall · 40 AB · 12 teammates",percentile:78}],development:[{label:"Average Exit Velocity",detail:"80.1 mph · Full Swing Intrasquad · 2026-09-16 · 12 teammates",percentile:22}],jumps:[{label:"Home to 1st",detail:"4.32 s to 4.18 s · 2026-09-15 to 2026-09-16 · Player Metrics",percentile:null}],missing:["Complete Blast Fall averages"],notes:["Percentiles compare at least five eligible teammates with the same metric, source, unit and period. Blue means a lower team rank; red means higher.","Body and spin comparisons are descriptive. No medical advice or invented training plan is included."],sections:[{id:"physicality",title:"Physicality",subtitle:"Latest recorded results",rows:[{...metric("Height","6′ 1″",70),source:"RENPHO",sample:null},{...metric("Weight","190 lb",45),source:"RENPHO",sample:null},{...metric("Body Fat %","12%",80),source:"RENPHO",sample:null},{...metric("Muscle Mass","160 lb",88),source:"RENPHO",sample:null},{...metric("RENPHO Body Score","88 points",null),source:"RENPHO",sample:null}]},{id:"hitting",title:"Hitting · In-Game",subtitle:"Latest profile results · Fall 2026",rows:[metric("Max Exit Velocity","105.2 mph",92),metric("Average Exit Velocity","80.1 mph",22),metric("Average Bat Speed","68.4 mph",80)],note:"In-Game and Practice use separate source comparisons."},{id:"arsenal",title:"Pitch Arsenal · In-Game",subtitle:"2026-09-16 · Staff-classified pitches",rows:[metric("Four-Seam Fastball · Average Velocity","82.2 mph",null),metric("Four-Seam Fastball · Max Velocity","86.1 mph",null),metric("Four-Seam Fastball · Average Spin","2110.4 rpm",null),metric("Four-Seam Fastball · Max Spin","2301.7 rpm",null)],note:"Spin is descriptive; a higher spin rate is not automatically better."},{id:"movement",title:"Movement Screening",subtitle:"Capstone · 2026-09-15",rows:Array.from({length:24},(_,i)=>({...metric(i%2?"Right Shoulder Internal Rotation":"Right Ankle Flexion",i%2?"65°":"3 / 5",null),source:"Capstone",sample:null,basis:i%2?"Range of motion":"Recorded rating",tone:i%3===0?"red":i%3===1?"yellow":"green"})),note:"Ratings use 1-5. Shoulder and hip range of motion use degrees. Ankle readings are ratings, not degrees."}]};
it("generates a real, paginated PDF with readable branded sections and no persistence by default",async()=>{
 const bytes=await createExitMeetingPdf(report,{meetingDate:"2026-10-01",talkingPoints:"Keep building consistent contact.\nReview the next testing date together."});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThanOrEqual(4);expect(pdf.getPageCount()).toBeLessThanOrEqual(8);expect(pdf.getTitle()).toContain("Fictional Boxer");expect(pdf.getPages().every(p=>p.getSize().width===612&&p.getSize().height===792)).toBe(true);expect(Buffer.from(bytes).subarray(0,4).toString()).toBe("%PDF");
 if(process.env.EXIT_MEETING_QA_DIR){await mkdir(process.env.EXIT_MEETING_QA_DIR,{recursive:true});await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,"fictional-exit-meeting.pdf"),bytes);}
});
it("handles long player names, unbroken notes, and a long table without clipping into another page",async()=>{
 const drawn=vi.spyOn(PDFPage.prototype,"drawText");
 const long={...report,name:"Fictional Extremely Long Compound Player Name for Layout Verification",sections:[{id:"long",title:"Extended Fictional Measurement Report",subtitle:"Synthetic pagination stress test",rows:Array.from({length:70},(_,i)=>metric(`Long descriptive measurement label ${i+1} with an exceptionally extended name`,"1234.5 mph",i%100))}]};
 const bytes=await createExitMeetingPdf(long,{meetingDate:"2026-10-01",talkingPoints:"Word".repeat(400)});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThan(8);expect(pdf.getPageCount()).toBeLessThan(25);
 for(const [text,options] of drawn.mock.calls){if(options?.font&&options.x!==undefined&&options.y!==undefined&&options.size!==undefined){expect(options.x).toBeGreaterThanOrEqual(38);expect(options.x+options.font.widthOfTextAtSize(text,options.size)).toBeLessThanOrEqual(574.1);expect(options.y).toBeGreaterThanOrEqual(20);expect(options.y+options.size).toBeLessThanOrEqual(780);}}
 drawn.mockRestore();
 if(process.env.EXIT_MEETING_QA_DIR)await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,"fictional-exit-meeting-stress.pdf"),bytes);
});
