import { expect, it, vi } from "vitest";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PDFDocument, PDFPage } from "pdf-lib";
vi.mock("server-only",()=>({}));
import { createExitMeetingPdf } from "@/lib/exit-meeting-pdf";
import type { ExitMeetingReport, ExitMeetingRow } from "@/lib/exit-meeting";

// Synthetic export used for visual QA; no actual player data or source report.
const metric=(label:string,value:string,percentile:number|null=80):ExitMeetingRow=>({label,value,source:"Fictional Full Swing · Intrasquad",date:"2026-09-16",basis:"Latest saved result",percentile,peers:percentile===null?null:12,sample:"28 readings"});
const report:ExitMeetingReport={format:"detailed",name:"Fictional Boxer",code:"PAC-9999",jersey:"#0",position:"SS / P",academicClass:"Senior",batsThrows:"Bats R / Throws R",season:"Fall 2026",generatedAt:"2026-09-27T12:00:00Z",lastTested:"2026-09-16",lastGameUpdate:"2026-09-20T04:00:00Z",strengths:[{label:"Max Exit Velocity",detail:"105.2 mph · Full Swing Intrasquad · 2026-09-16 · 12 teammates",percentile:92},{label:"AVG · Hitting",detail:".350 · QPA Fall · 40 AB · 12 teammates",percentile:78}],development:[{label:"Average Exit Velocity",detail:"80.1 mph · Full Swing Intrasquad · 2026-09-16 · 12 teammates",percentile:22}],jumps:[{label:"Home to 1st",detail:"4.32 s to 4.18 s · 2026-09-15 to 2026-09-16 · Player Metrics",percentile:null}],missing:["Complete Blast Fall averages"],notes:["Percentiles compare at least five eligible teammates with the same metric, source, unit and period. Blue means a lower team rank; red means higher.","Body and spin comparisons are descriptive. No medical advice or invented training plan is included."],sections:[{id:"physicality",title:"Physicality",subtitle:"Latest recorded results",rows:[{...metric("Height","6′ 1″",70),source:"RENPHO",sample:null},{...metric("Weight","190 lb",45),source:"RENPHO",sample:null},{...metric("Body Fat %","12%",80),source:"RENPHO",sample:null},{...metric("Muscle Mass","160 lb",88),source:"RENPHO",sample:null},{...metric("RENPHO Body Score","88 points",null),source:"RENPHO",sample:null}]},{id:"hitting",title:"Hitting · In-Game",subtitle:"Latest profile results · Fall 2026",rows:[metric("Max Exit Velocity","105.2 mph",92),metric("Average Exit Velocity","80.1 mph",22),metric("Average Bat Speed","68.4 mph",80)],note:"In-Game and Practice use separate source comparisons."},{id:"arsenal",title:"Pitch Arsenal · In-Game",subtitle:"2026-09-16 · Staff-classified pitches",rows:[metric("Four-Seam Fastball · Average Velocity","82.2 mph",null),metric("Four-Seam Fastball · Max Velocity","86.1 mph",null),metric("Four-Seam Fastball · Average Spin","2110.4 rpm",null),metric("Four-Seam Fastball · Max Spin","2301.7 rpm",null)],note:"Spin is descriptive; a higher spin rate is not automatically better."},{id:"movement",title:"Movement Screening",subtitle:"Capstone · 2026-09-15",rows:Array.from({length:24},(_,i)=>({...metric(i%2?"Right Shoulder Internal Rotation":"Right Ankle Flexion",i%2?"65°":"3 / 5",null),source:"Capstone",sample:null,basis:i%2?"Range of motion":"Recorded rating",tone:i%3===0?"red":i%3===1?"yellow":"green"})),note:"Ratings use 1-5. Shoulder and hip range of motion use degrees. Ankle readings are ratings, not degrees."}]};
it("generates a real, paginated PDF with readable branded sections and no persistence by default",async()=>{
 const bytes=await createExitMeetingPdf(report,{meetingDate:"2026-10-01",talkingPoints:"Keep building consistent contact.\nReview the next testing date together."});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThanOrEqual(4);expect(pdf.getPageCount()).toBeLessThanOrEqual(8);expect(pdf.getTitle()).toContain("Fictional Boxer");expect(pdf.getPages().every(p=>p.getSize().width===612&&p.getSize().height===792)).toBe(true);expect(Buffer.from(bytes).subarray(0,4).toString()).toBe("%PDF");
 if(process.env.EXIT_MEETING_QA_DIR){await mkdir(process.env.EXIT_MEETING_QA_DIR,{recursive:true});await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,"fictional-exit-meeting.pdf"),bytes);}
});
it("handles long player names, unbroken notes, and a long table without clipping into another page",async()=>{
 const drawn=vi.spyOn(PDFPage.prototype,"drawText");
 const long={...report,name:"Fictional Extremely Long Compound Player Name for Layout Verification",sections:[{id:"long",title:"Extended Fictional Measurement Report",subtitle:"Synthetic pagination stress test",rows:Array.from({length:70},(_,i)=>metric(`Long descriptive measurement label ${i+1} with an exceptionally extended name`,"1234.5 mph",i%100))}]};
 const bytes=await createExitMeetingPdf(long,{meetingDate:"2026-10-01",talkingPoints:"Word".repeat(400)});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThan(8);expect(pdf.getPageCount()).toBeLessThan(25);
 for(const [text,options] of drawn.mock.calls){if(options?.font&&options.x!==undefined&&options.y!==undefined&&options.size!==undefined){expect(options.x).toBeGreaterThanOrEqual(38);expect(options.x+options.font.widthOfTextAtSize(text,options.size)).toBeLessThanOrEqual(574.1);expect(options.y).toBeGreaterThanOrEqual(20);expect(options.y+options.size).toBeLessThanOrEqual(780);}}
 drawn.mockRestore();
 if(process.env.EXIT_MEETING_QA_DIR)await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,"fictional-exit-meeting-stress.pdf"),bytes);
});

const compactBase:ExitMeetingReport={...report,format:"meeting",missing:[],sections:[
 {id:"physicality",title:"Physicality",subtitle:"Latest recorded measurements",rows:[...report.sections[0].rows,...["Dominant Grip","Non-Dominant Grip"].map(label=>({...metric(label,"115 lb",72),source:"Player Metrics",basis:"Latest profile result",sample:null}))]},
 {id:"game-hitting",title:"Game Stats · Hitting",subtitle:"Fall to date · Current approved team-sheet totals",rows:["AVG","OBP","QPA %","Hard Hit %","BB %","K %","Home Runs","Stolen Bases"].map((label,index)=>({...metric(label,index<2?".350":index<6?"25.0%":"3",70+index),source:"QPA Fall Sheet",date:"2026-09-26",basis:"Updated snapshot",sample:index===0?"40 AB":"48 plate appearances"}))},
 {id:"game-pitching",title:"Game Stats · Pitching",subtitle:"Fall to date · Current approved team-sheet totals",rows:["K/9","BB/9","Runs/9","Strike %","Weak Contact %","Hard Contact %"].map((label,index)=>({...metric(label,index<3?"6.00":"65.0%",80-index),source:"Pitching Fall Sheet",date:"2026-09-26",basis:"Updated snapshot",sample:index<3?"27 outs":index===3?"100 pitches":"36 classified contacts"}))},
 {id:"hitting",title:"Hitting · In-Game",subtitle:"Latest saved profile results · Fall 2026",rows:[...report.sections[1].rows,metric("Max Bat Speed","72.3 mph",80),metric("Max Distance","375.1 ft",75)].map(row=>({...row,sample:"Session sample not shown"}))},
 {id:"blast-fall",title:"Hitting · Blast Practice",subtitle:"Swing-weighted averages across reviewed, non-overlapping weekly exports",rows:["Bat Speed (Practice)","Hand Speed","Attack Angle","Early Connection","Vertical Bat Angle"].map((label,index)=>({...metric(label,index<2?"68.4 mph":index===4?"-24.0 °":"20.0 °",null),source:"Blast Motion · Practice",date:"2026-09-13 to 2026-09-26",basis:"Fall weighted average",sample:"220 swings · 2 reports"}))},
 {id:"testing",title:"Running & Position Throwing",subtitle:"Best trial and trial average",rows:["Home to 1st","Home to 2nd","Boxer T"].map(label=>({...metric(label,"4.15 s",75),source:"Player Metrics",basis:"Best time · Average 4.25 s",sample:"3 trials"}))},
 {id:"arsenal",title:"Pitch Arsenal · In-Game",subtitle:"Full Swing Intrasquad · Fall averages and bests",rows:["Fastball","Slider","Curveball","Changeup"].flatMap(pitch=>["Velocity","Spin"].map(family=>({...metric(`${pitch} · ${family}`,family==="Velocity"?"81.5 avg / 86.0 max mph":"2050.5 avg / 2300.2 max rpm",null),source:"Full Swing · Intrasquad",date:"2026-09-11 to 2026-09-23",basis:"Fall weighted average / best",sample:family==="Velocity"?"40 velocity readings · 2 sessions":"36 spin readings · 2 sessions"}))),note:"Average / max stay within the same pitch and source. Spin describes the pitch; higher is not automatically better."},
],notes:["Percentiles compare at least five teammates in the same test, source, unit and period. Red is higher, blue lower. Unranked means no verified comparison. Body and spin comparisons are descriptive.","Game stats are Fall to date. Test values are latest, timed trials use best time, and pitch averages are weighted by recorded readings. In-Game and Practice are separate.","Detailed Report includes all weekly Blast/P95, RENPHO, movement, supporting counts and saved pitch sessions."]};

it("keeps populated hitter, pitcher, and two-way meeting summaries within four readable pages",async()=>{
 const variants=[{name:"hitter",report:{...compactBase,position:"SS",sections:compactBase.sections.filter(s=>!["game-pitching","arsenal"].includes(s.id))}},{name:"pitcher",report:{...compactBase,position:"P",strengths:[{label:"K/9 · Pitching",detail:"12.00 · 27 outs · 12 teammates · Updated 2026-09-26",percentile:92}],development:[],jumps:[],sections:compactBase.sections.filter(s=>["physicality","game-pitching","arsenal"].includes(s.id))}},{name:"two-way",report:compactBase}];
 const drawn=vi.spyOn(PDFPage.prototype,"drawText");
 for(const variant of variants){const bytes=await createExitMeetingPdf(variant.report,{meetingDate:"2026-10-01",talkingPoints:"Review the strongest results and select the next focus together."});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThanOrEqual(2);expect(pdf.getPageCount()).toBeLessThanOrEqual(4);if(process.env.EXIT_MEETING_QA_DIR){await mkdir(process.env.EXIT_MEETING_QA_DIR,{recursive:true});await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,`fictional-meeting-summary-${variant.name}.pdf`),bytes);}}
 for(const [text,options] of drawn.mock.calls){if(options?.font&&options.x!==undefined&&options.y!==undefined&&options.size!==undefined){expect(options.x).toBeGreaterThanOrEqual(38);expect(options.x+options.font.widthOfTextAtSize(text,options.size)).toBeLessThanOrEqual(574.1);expect(options.y).toBeGreaterThanOrEqual(20);expect(options.y+options.size).toBeLessThanOrEqual(780);}}
 drawn.mockRestore();
});
it("wraps a long name and maximum-length coach notes in the compact report without clipping",async()=>{
 const drawn=vi.spyOn(PDFPage.prototype,"drawText");
 const bytes=await createExitMeetingPdf({...compactBase,name:"Fictional Very Long Compound Player Name for Meeting Layout Verification"},{meetingDate:"2026-10-01",talkingPoints:"Review".repeat(266)});
 const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeLessThanOrEqual(5);
 for(const [text,options] of drawn.mock.calls){if(options?.font&&options.x!==undefined&&options.y!==undefined&&options.size!==undefined){expect(options.x).toBeGreaterThanOrEqual(38);expect(options.x+options.font.widthOfTextAtSize(text,options.size)).toBeLessThanOrEqual(574.1);expect(options.y).toBeGreaterThanOrEqual(20);expect(options.y+options.size).toBeLessThanOrEqual(780);}}
 drawn.mockRestore();if(process.env.EXIT_MEETING_QA_DIR)await writeFile(path.join(process.env.EXIT_MEETING_QA_DIR,"fictional-meeting-summary-stress.pdf"),bytes);
});
