import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
const fake=vi.hoisted(()=>({guard:vi.fn(),rpc:vi.fn(),revalidate:vi.fn()}));
vi.mock("@/lib/auth",()=>({requireImportAccess:fake.guard}));vi.mock("next/cache",()=>({revalidatePath:fake.revalidate}));vi.mock("next/navigation",()=>({redirect:(path:string)=>{throw new Error(`REDIRECT:${path}`);}}));
import { importGameSnapshot } from "@/app/(workspace)/imports/game-stats/actions";
import { validateGameImport } from "@/lib/game-import";
const id="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const row=()=>({athleteCode:"PAC-0001",metric:"pa",value:0,unit:"count",scope:"cumulative_fall",eventId:null,playedOn:null,sourceRow:2,sourceColumn:2,derivedFrom:[]});
const snapshot=()=>({source:"qpa_fall_2026",contentHash:"a".repeat(64),fetchedAt:"2026-09-13T12:00:00Z",observations:[row()]});
const form=()=>{const f=new FormData();f.set("snapshot",JSON.stringify(snapshot()));f.set("confirm","yes");return f;};
beforeEach(()=>{vi.resetAllMocks();vi.useFakeTimers();vi.setSystemTime(new Date("2026-09-14T12:00:00Z"));fake.guard.mockResolvedValue({supabase:{rpc:fake.rpc}});fake.rpc.mockResolvedValue({data:{snapshot_id:id,changed:true,observations:1},error:null});});afterEach(()=>vi.useRealTimers());
describe("game import action boundary",()=>{
 it.each(["/login","/access-denied","/overview?preview=read-only"])("requires trusted import access before touching payload: %s",async path=>{fake.guard.mockRejectedValue(new Error(path));await expect(importGameSnapshot(null as unknown as FormData)).rejects.toThrow(path);expect(fake.rpc).not.toHaveBeenCalled();});
 it("rechecks current staff before saving",async()=>{fake.guard.mockResolvedValueOnce({supabase:{rpc:fake.rpc}}).mockRejectedValueOnce(new Error("revoked"));await expect(importGameSnapshot(form())).rejects.toThrow("revoked");expect(fake.rpc).not.toHaveBeenCalled();});
 it.each(["duplicate","unchecked","oversize","nonarray","source"])("rejects malformed or unreviewed %s without RPC",async kind=>{const f=form();if(kind==="duplicate")f.append("snapshot","{}");if(kind==="unchecked")f.delete("confirm");if(kind==="oversize")f.set("snapshot","é".repeat(524289));if(kind==="nonarray")f.set("snapshot",JSON.stringify({...snapshot(),observations:{}}));if(kind==="source")f.set("snapshot",JSON.stringify({...snapshot(),source:"constructor"}));await expect(importGameSnapshot(f)).rejects.toThrow(/error=review|error=input/);expect(fake.rpc).not.toHaveBeenCalled();});
 it("submits only canonical numeric fields and follows a fixed verified receipt redirect",async()=>{const f=form();f.set("snapshot",JSON.stringify({...snapshot(),rawNames:["Fictional Player"],observations:[{...row(),privateText:"Fictional excluded field"}]}));await expect(importGameSnapshot(f)).rejects.toThrow(`REDIRECT:/imports/game-stats?saved=${id}`);expect(fake.rpc).toHaveBeenCalledExactlyOnceWith("import_game_snapshot",{p_source:"qpa_fall_2026",p_hash:"a".repeat(64),p_fetched_at:snapshot().fetchedAt,p_rows:[row()]});expect(fake.revalidate.mock.calls).toEqual([["/game-stats"],["/athletes","layout"]]);});
 it.each(["error","throw","badreceipt"])("does not claim success or retry an uncertain %s",async kind=>{if(kind==="throw")fake.rpc.mockRejectedValue(new Error("uncertain"));else fake.rpc.mockResolvedValue(kind==="error"?{data:null,error:{message:"fictional"}}:{data:{snapshot_id:id,changed:true,observations:2},error:null});await expect(importGameSnapshot(form())).rejects.toThrow("error=save");expect(fake.rpc).toHaveBeenCalledTimes(1);expect(fake.revalidate).not.toHaveBeenCalled();});
 it("rejects future provenance, invalid rate inputs, and mixed date/source evidence before transport",()=>{for(const changes of [{contentHash:"a".repeat(64)+"\n"},{fetchedAt:"2026-09-15T12:00:00Z"},{observations:[row(),row()]},{observations:[{...row(),value:-1}]},{observations:[{...row(),metric:"qpa_pct",unit:"%",sourceColumn:8,derivedFrom:[3,2],value:10}]}])expect(()=>validateGameImport({...snapshot(),...changes})).toThrow();});
});
