import { afterEach,beforeEach,describe,expect,it } from "vitest";
import { mkdtempSync,readFileSync,writeFileSync,statSync,rmSync,existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { GAME_SOURCES,GAME_CAPTURE_SHAPES } from "@/lib/game-source-config";
import { QPA_HEADERS } from "@/lib/game-source";
const repo=fileURLToPath(new URL("..",import.meta.url));let folder:string;
const capture=()=>({source:"qpa_fall_2026",range:GAME_CAPTURE_SHAPES.qpa_fall_2026.range,fetchedAt:new Date().toISOString(),response:{spreadsheetId:GAME_SOURCES.qpa_fall_2026.spreadsheetId,sheets:[{properties:{sheetId:GAME_SOURCES.qpa_fall_2026.sheetId,title:"2026 - Fall",gridProperties:{rowCount:968,columnCount:33}},data:[{rowData:[{values:QPA_HEADERS.map(stringValue=>({userEnteredValue:{stringValue:String(stringValue)}}))}]}]}]}});
const run=(input:string,output:string)=>spawnSync(process.execPath,[resolve(repo,"scripts/prepare-game-snapshot.mjs"),"--source","qpa_fall_2026","--input",input,"--output",output],{encoding:"utf8"});
beforeEach(()=>{folder=mkdtempSync(resolve(tmpdir(),"pacu-fictional-game-"));});afterEach(()=>rmSync(folder,{recursive:true,force:true}));
describe("private game preparation commands",()=>{
 it("runs with the actual Node runtime, writes only private exclusive outputs and stable source hashes",()=>{const input=resolve(folder,"input.json"),output=resolve(folder,"first.json"),second=resolve(folder,"second.json");writeFileSync(input,JSON.stringify(capture()),{mode:0o600});const first=run(input,output);expect(first.status).toBe(0);const status=JSON.parse(first.stdout);expect(status).toMatchObject({observations:0,populatedRows:0,errors:0,canImport:false,mappingsReviewed:false});expect(statSync(output).mode&0o777).toBe(0o600);const raw=JSON.parse(readFileSync(input,"utf8"));raw.fetchedAt=new Date(Date.now()-1000).toISOString();writeFileSync(input,JSON.stringify(raw));expect(JSON.parse(run(input,second).stdout).contentHash).toBe(status.contentHash);expect(run(input,output).status).toBe(1);});
 it("does not expose malformed private JSON in failure output",()=>{const input=resolve(folder,"input.json");writeFileSync(input,'{"fictional_private_name":"Fictional Confidential",broken');const result=run(input,resolve(folder,"output.json"));expect(result.status).toBe(1);expect(result.stderr).toContain("not valid JSON");expect(result.stderr).not.toContain("Fictional Confidential");});
 it("refuses an inside-repo ..private path without creating it",()=>{const input=resolve(folder,"input.json"),output=resolve(repo,"..private-game-fixture","output.json");writeFileSync(input,JSON.stringify(capture()));expect(existsSync(resolve(repo,"..private-game-fixture"))).toBe(false);expect(run(input,output).status).toBe(1);expect(existsSync(resolve(repo,"..private-game-fixture"))).toBe(false);const writer=spawnSync(process.execPath,[resolve(repo,"scripts/write-private-game-capture.mjs"),output],{input:JSON.stringify(capture())+"\n",encoding:"utf8"});expect(writer.status).toBe(1);expect(existsSync(resolve(repo,"..private-game-fixture"))).toBe(false);});
 it("streams connector JSON through stdin without echoing source cells",()=>{const output=resolve(folder,"captured.json"),raw=capture();raw.response.sheets[0].data[0].rowData.push({values:[{userEnteredValue:{stringValue:"Fictional Confidential"}}]});const saved=spawnSync(process.execPath,[resolve(repo,"scripts/write-private-game-capture.mjs"),output],{input:JSON.stringify(raw)+"\n",encoding:"utf8"});expect(saved.status).toBe(0);expect(JSON.parse(saved.stdout).written).toBe(true);expect(saved.stdout+saved.stderr).not.toContain("Fictional Confidential");expect(statSync(output).mode&0o777).toBe(0o600);});
});
