import { describe,it,expect } from "vitest";
import { buildGraphicsCard,graphicsCaption,graphicsGroupKey,graphicsMetricGroups,selectedGraphicsMetrics,type GraphicsCardOptions } from "@/lib/graphics-card";
import { graphicsExample as player,graphicsSecond as second,graphicsBoards } from "./fixtures/graphics";
const options:GraphicsCardOptions={template:"player",player,second,metrics:player.metrics,board:graphicsBoards[0],topCount:5,arsenalContext:"Game",trendKey:"muscle",headline:""};
describe("sharing-card evidence",()=>{
 it("separates exact source/context groups and requires verified percentiles",()=>{const other={...player.metrics[0],source:"Full Swing Game",percentile:null};const data={...player,metrics:[...player.metrics,other]};expect(graphicsMetricGroups(data.metrics)).toHaveLength(2);expect(selectedGraphicsMetrics(data,graphicsGroupKey(other),[],"percentiles")).toEqual([]);expect(selectedGraphicsMetrics(data,graphicsGroupKey(other),[],"player")).toEqual([other]);});
 it("exports no source identities, email or raw readings",()=>{const card=buildGraphicsCard(options)!;const serialized=JSON.stringify(card);expect(serialized).not.toContain(player.player.id);expect(serialized).not.toContain(player.player.code);expect(serialized).not.toContain("file_hash");expect(card.metrics[0].value).toBe("69.8 mph");expect(card.metrics[0].sample).toContain("124 swings");});
 it("preserves original leaderboard ties and samples",()=>{const card=buildGraphicsCard({...options,template:"leaderboard",topCount:10})!;expect(card.ranking).toHaveLength(10);expect(card.ranking?.map(r=>r.rank).slice(0,3)).toEqual([1,1,3]);expect(card.ranking?.[0].sample).toBe("124 swings · 2026-09-20");});
 it("will not compare different snapshots, contexts or units",()=>{for(const changed of [{key:"different-snapshot"},{context:"In-Game"},{unit:"m/s"},{source:"Other"}]){const mismatch={...second,metrics:second.metrics.map(m=>({...m,...changed}))};expect(buildGraphicsCard({...options,template:"comparison",second:mismatch})).toBeNull();}expect(buildGraphicsCard({...options,template:"comparison",second:player})).toBeNull();});
 it("keeps comparison sample/date beside each number with no manufactured winner",()=>{const card=buildGraphicsCard({...options,template:"comparison"})!;expect(card.comparison?.rows[0]).toMatchObject({a:"69.8 mph",b:"67.8 mph",aSample:"124 swings · 2 reports · 2026-09-20",bSample:"93 swings · 2 reports · 2026-09-20"});expect(JSON.stringify(card)).not.toMatch(/winner|Group Best/);});
 it("preserves pitch-family average counts, independent windows and max dates",()=>{const card=buildGraphicsCard({...options,template:"arsenal"})!;expect(card.pitches).toHaveLength(2);expect(card.pitches?.[1].sample).toContain("24 velo / 20 spin average readings");expect(card.pitches?.[1].context).toContain("Spin average: 2026-09-23.");expect(card.pitches?.[1].context).toContain("Max velo: 2026-09-11.");expect(card.footerNotes?.join(" ")).toContain("latest verified average");expect(buildGraphicsCard({...options,template:"arsenal",arsenalContext:"Practice"})).toBeNull();});
 it("keeps formula and cohort caveats on images and copied captions",()=>{const metric={...player.metrics[0],key:"batting_est_slg"};const card=buildGraphicsCard({...options,template:"percentiles",metrics:[metric]})!;expect(graphicsCaption(card)).toContain("double or triple as two bases");expect(graphicsCaption(card)).toContain("not national rankings");expect(graphicsCaption(card)).toContain("Not an official university application");});
 it("withholds missing stats and single-test progress instead of inventing a chart",()=>{expect(buildGraphicsCard({...options,metrics:[]})).toBeNull();expect(buildGraphicsCard({...options,template:"trend",player:{...player,trends:[{...player.trends[0],points:[player.trends[0].points[0]]}]}})).toBeNull();expect(buildGraphicsCard({...options,template:"dashboard",player:null})?.metrics).toHaveLength(6);});
});
