import {createElement} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {describe,it,expect} from "vitest";
import {inningsToOuts} from "@/lib/game-source";
import {pitchingRates,pitchSplits,formatInnings} from "@/lib/pitching-stats";
import {GameLeaderboard} from "@/components/game-leaderboard";
import {teamGameSummary} from "@/lib/team-game-stats";
import type {SharedGameStat} from "@/lib/game-server";
const rows=(counts:Record<string,number>):SharedGameStat[]=>Object.entries(counts).map(([metric,value])=>({athlete_id:"fictional",source:"pitching_fall_2026",metric,value,unit:"count",scope:"pitching_event",event_id:"fall-2026-week-1",played_on:null,source_row:40,source_column:1,derived_from:[],snapshot_id:"fictional",fetched_at:"2026-09-14T18:00:00Z",content_hash:"a".repeat(64)}));
describe("pitching rate definitions",()=>{
 it("uses exact outs, including partial innings",()=>{expect(inningsToOuts(1.1)).toBe(4);expect(inningsToOuts("1.2")).toBe(5);expect(inningsToOuts(0)).toBe(0);expect(inningsToOuts(1.33)).toBe(4);expect(inningsToOuts(1.67)).toBe(5);expect(formatInnings(5)).toBe("1.2");for(const bad of [1.3,1.5,"1/3","=1.2",-1,Infinity,null])expect(inningsToOuts(bad)).toBeNull();});
 it("calculates per-nine rates without fabricating earned runs or dividing by zero",()=>{const rates=pitchingRates(rows({innings_outs:5,k:3,bb_outcome:1,r:4}));expect(rates.map(r=>r.value)).toEqual([16.2,5.4,null]);expect(pitchingRates(rows({innings_outs:5,earned_runs:2}))[2].value).toBe(10.8);expect(pitchingRates(rows({innings_outs:0,k:3}))[0].value).toBeNull();expect(pitchingRates(rows({innings_outs:3,k:0}))[0].value).toBe(0);});
 it("uses family denominators, preserves missing counts, and rejects inconsistent totals",()=>{const split=pitchSplits(rows({pitches:20,fb:10,fb_k:7,bb_pitch_family:5,bb_pitch_family_k:2}));expect(split[0]).toMatchObject({usage:50,strikePct:70});expect(split[1]).toMatchObject({usage:25,strikePct:40});expect(split[2]).toMatchObject({pitches:null,usage:null,strikePct:null});expect(pitchSplits(rows({pitches:5,fb:10,fb_k:11}))[0]).toMatchObject({usage:null,strikePct:null});});
 it("combines team counts and outs instead of averaging player per-nine rates",()=>{const a=rows({innings_outs:3,k:1,bb_outcome:0}),b=rows({innings_outs:6,k:3,bb_outcome:2}).map(r=>({...r,athlete_id:"fictional-second"}));const s=teamGameSummary([...a,...b],"pitching_fall_2026");expect(s.rates.find(r=>r.metric==="pitching_k9")?.value).toBe(12);expect(s.rates.find(r=>r.metric==="pitching_bb9")?.value).toBe(6);});
 it("separates hitting and pitching leaderboard rows",()=>{const base={metric:"strike_pct",source:"pitching_fall_2026",eventId:"fall-2026-week-1",playedOn:null,value:50,unit:"%",rank:1,name:"Fictional Pitcher",code:"PAC-0001",profileId:null,updatedAt:"2026-09-14T18:00:00Z",percentile:null,sampleSize:1};const data=[base,{...base,source:"qpa_fall_2026",metric:"batting_avg",eventId:"",name:"Fictional Hitter",unit:"avg",value:.5}];const pitching=renderToStaticMarkup(createElement(GameLeaderboard,{rows:data,discipline:"pitching"}));expect(pitching).toContain("Fictional Pitcher");expect(pitching).not.toContain("Fictional Hitter");const hitting=renderToStaticMarkup(createElement(GameLeaderboard,{rows:data,discipline:"hitting"}));expect(hitting).toContain("Fictional Hitter");expect(hitting).not.toContain("Fictional Pitcher");});
});
