"use client";
import { useId, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeftRight, RotateCcw, ChartScatter } from "lucide-react";
import { StatInfo } from "@/components/stat-info";
import { formatHeight } from "@/lib/measurement-display";
import { COLOR_GROUPS, analyticsVariables, readingsForPeriod, pairAnalytics, pointGroup, prettyGroup, linearFit, chartDomain, type AnalyticsDataset, type AnalyticsPoint, type AnalyticsVariable, type ColorGroup } from "@/lib/analytics";
import styles from "./analytics.module.css";

const COLORS=["#4996d5","#d5ae45","#dd8758","#90a657","#cf7fb6"];
const number=(n:number)=>new Intl.NumberFormat("en-US",{maximumSignificantDigits:4}).format(n);
const date=(d:string)=>new Date(`${d}T00:00:00Z`).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"});
const reading=(r:AnalyticsPoint["x"])=>r.metric==="height"?`${formatHeight(r.value,r.unit)??`${number(r.value)} ${r.unit}`} (${number(r.value)} ${r.unit})`:`${number(r.value)} ${r.unit}`;
function Mark({index,cx,cy,size=6}:{index:number;cx:number;cy:number;size?:number}) {
  const common={fill:COLORS[index%COLORS.length],stroke:"var(--surface-panel)",strokeWidth:1.5};
  if(Math.floor(index/COLORS.length)%3===1)return <rect x={cx-size} y={cy-size} width={size*2} height={size*2} rx={1} {...common}/>;
  if(Math.floor(index/COLORS.length)%3===2)return <path d={`M${cx},${cy-size-2} L${cx+size+1},${cy+size} L${cx-size-1},${cy+size} Z`} {...common}/>;
  return <circle cx={cx} cy={cy} r={size} {...common}/>;
}
export function AnalyticsExplorer({data}:{data:AnalyticsDataset}) {
  const chartId=useId(),[period,setPeriod]=useState<"fall"|"earlier">("fall"),[xChoice,setXChoice]=useState(""),[yChoice,setYChoice]=useState(""),[group,setGroup]=useState<ColorGroup>("academicClass"),[classFilter,setClassFilter]=useState(""),[positionFilter,setPositionFilter]=useState(""),[maxGap,setMaxGap]=useState(30),[hidden,setHidden]=useState<string[]>([]),[active,setActive]=useState<string|null>(null);
  const readings=useMemo(()=>readingsForPeriod(data.readings,period),[data.readings,period]);
  const variables=useMemo(()=>analyticsVariables(readings),[readings]);
  const x=variables.find(v=>v.key===xChoice)??variables.find(v=>v.metric==="weight")??variables[0];
  const y=variables.find(v=>v.key===yChoice)??variables.find(v=>v.metric==="muscle_mass"&&v.key!==x?.key)??variables.find(v=>v.key!==x?.key);
  const eligible=data.players.filter(p=>(!classFilter||(p.academicClass||"__unknown")===classFilter)&&(!positionFilter||(p.position||"__unknown")===positionFilter));
  const paired=pairAnalytics(eligible,readings,x?.key??"",y?.key??"",maxGap);
  const classOrder=["Freshman","Sophomore","Junior","Senior","Graduate","Not Listed"];
  const groups=[...new Set(data.players.map(p=>pointGroup(p,group)))].sort((a,b)=>group==="academicClass" ? (classOrder.indexOf(a)<0?99:classOrder.indexOf(a))-(classOrder.indexOf(b)<0?99:classOrder.indexOf(b))||a.localeCompare(b):a.localeCompare(b));
  const points=paired.points.filter(p=>!hidden.includes(pointGroup(p.player,group)));
  const fit=x?.key!==y?.key?linearFit(points.map(p=>({x:p.x.value,y:p.y.value}))):null;
  const selected=points.find(p=>p.player.id===active);
  const xDomain=chartDomain(points.map(p=>p.x.value)),yDomain=chartDomain(points.map(p=>p.y.value));
  const px=(n:number)=>76+(n-xDomain[0])/(xDomain[1]-xDomain[0])*780,py=(n:number)=>408-(n-yDomain[0])/(yDomain[1]-yDomain[0])*360;
  const minX=points.length?Math.min(...points.map(p=>p.x.value)):0,maxX=points.length?Math.max(...points.map(p=>p.x.value)):1;
  const fitted=(v:number)=>fit?fit.meanY+fit.slope*(v-fit.meanX):0;
  const optionLabel=(v:AnalyticsVariable)=>`${v.label} · ${v.unit} · ${v.source} (${v.count})`;
  function reset(){setXChoice("");setYChoice("");setPeriod("fall");setGroup("academicClass");setClassFilter("");setPositionFilter("");setMaxGap(30);setHidden([]);setActive(null);}
  return <div className={styles.explorer}>
    <section className={`panel ${styles.controls}`} aria-label="Analytics controls">
      <div className={styles.axes}><label>X-Axis Variable<select value={x?.key??""} onChange={e=>{setXChoice(e.target.value);setActive(null);}}><option value="" disabled>Waiting for measurements</option>{variables.map(v=><option key={v.key} value={v.key}>{optionLabel(v)}</option>)}</select></label><button className="btn btn-secondary" type="button" aria-label="Swap X and Y axes" disabled={!x||!y} onClick={()=>{if(x&&y){setXChoice(y.key);setYChoice(x.key);}}}><ArrowLeftRight size={18}/></button><label>Y-Axis Variable<select value={y?.key??""} onChange={e=>{setYChoice(e.target.value);setActive(null);}}><option value="" disabled>Choose another measurement</option>{variables.map(v=><option key={v.key} value={v.key}>{optionLabel(v)}</option>)}</select></label></div>
      <div className={styles.filters}><label>Color By<select value={group} onChange={e=>{setGroup(e.target.value as ColorGroup);setHidden([]);}}>{COLOR_GROUPS.map(g=><option key={g.key} value={g.key}>{g.label}</option>)}</select></label><label>Class<select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="">All Classes</option>{[...new Set(data.players.map(p=>p.academicClass))].sort().map(c=><option key={c||"unknown"} value={c||"__unknown"}>{prettyGroup(c)||"Not Listed"}</option>)}</select></label><label>Primary Position<select value={positionFilter} onChange={e=>setPositionFilter(e.target.value)}><option value="">All Positions</option>{[...new Set(data.players.map(p=>p.position))].sort().map(p=><option key={p||"unknown"} value={p||"__unknown"}>{p||"Not Listed"}</option>)}</select></label><label>Testing Period<select value={period} onChange={e=>{setPeriod(e.target.value as "fall"|"earlier");setActive(null);}}><option value="fall">Fall 2026</option><option value="earlier">Jun–Aug 2026 · Body</option></select></label><label>Maximum Test-Date Gap<select value={maxGap} onChange={e=>setMaxGap(Number(e.target.value))}><option value={0}>Same Day</option><option value={7}>7 Days</option><option value={30}>30 Days</option><option value={90}>90 Days</option><option value={366}>Any in This Period</option></select></label><button type="button" className="btn btn-secondary" onClick={reset}><RotateCcw size={15}/>Reset</button></div>
    </section>
    <section className={`panel ${styles.chartPanel}`} aria-label="Correlation analysis">
      <div className={styles.heading}><div><p className="eyebrow text-pacu-red">Player Relationships</p><h2>{x&&y?`${x.label} vs. ${y.label}`:"Choose Two Measurements"}</h2><p className="muted">{period==="fall"?"Fall 2026":"June–August 2026"} · One dot per player · Latest test per variable</p></div><div className={styles.scores} aria-live="polite"><div><span>Paired Players</span><strong>{points.length}</strong></div><div><span>Pearson r</span><strong>{fit?.r==null?"—":fit.r.toFixed(2)}</strong></div><div><span>R²</span><strong>{fit?.rSquared==null?"—":fit.rSquared.toFixed(2)}</strong></div></div></div>
      {x&&y&&<div className={styles.sourceLine}><span><b>X:</b> {x.label} ({x.unit}) · {x.source}<StatInfo metric={x.metric} label={x.label}/></span><span><b>Y:</b> {y.label} ({y.unit}) · {y.source}<StatInfo metric={y.metric} label={y.label}/></span></div>}
      {paired.points.length>0&&x?.key!==y?.key&&<div className={styles.legend} role="group" aria-label="Show or hide color groups">{groups.map((g,index)=>{const count=paired.points.filter(p=>pointGroup(p.player,group)===g).length;return <button key={g} type="button" aria-pressed={!hidden.includes(g)} disabled={!count} onClick={()=>setHidden(prev=>prev.includes(g)?prev.filter(v=>v!==g):[...prev,g])}><svg width="20" height="20" aria-hidden="true"><Mark index={index} cx={10} cy={10} size={5}/></svg>{g}<span>{count}</span></button>;})}</div>}
      {x?.key===y?.key&&x?<p className="notice">Choose two different variables to explore a relationship.</p>:!points.length?<div className={styles.empty}><ChartScatter size={36} aria-hidden="true"/><h3>No Paired Results Yet</h3><p>Choose measurements recorded for the same players, or adjust the class, position, and date-gap controls. New imported measurements become available when this page is refreshed.</p></div>:<>
        <div className={styles.plotScroll}><svg className={styles.plot} viewBox="0 0 900 480" role="group" aria-label={`${x?.label} versus ${y?.label} scatterplot; ${points.length} players`}>
          <defs><clipPath id={chartId}><rect x="76" y="48" width="780" height="360"/></clipPath></defs>
          {[0,1,2,3,4].map(i=>{const xv=xDomain[0]+(xDomain[1]-xDomain[0])*i/4,yv=yDomain[0]+(yDomain[1]-yDomain[0])*i/4;return <g key={i}><line x1={px(xv)} x2={px(xv)} y1="48" y2="408" className={styles.grid}/><line x1="76" x2="856" y1={py(yv)} y2={py(yv)} className={styles.grid}/><text x={px(xv)} y="435" textAnchor="middle">{number(xv)}</text><text x="65" y={py(yv)+4} textAnchor="end">{number(yv)}</text></g>;})}
          <path d="M76 48 V408 H856" className={styles.axis}/><text x="466" y="470" textAnchor="middle" className={styles.axisLabel}>{x?.label} ({x?.unit})</text><text transform="translate(18 228) rotate(-90)" textAnchor="middle" className={styles.axisLabel}>{y?.label} ({y?.unit})</text>
          {fit&&<line clipPath={`url(#${chartId})`} x1={px(minX)} y1={py(fitted(minX))} x2={px(maxX)} y2={py(fitted(maxX))} className={styles.fit}><title>Least-squares best-fit line for all visible players</title></line>}
          {points.map(p=><g key={p.player.id} tabIndex={0} role="button" className={styles.point} aria-label={`${p.player.name}: ${x?.label} ${reading(p.x)}, ${y?.label} ${reading(p.y)}; ${pointGroup(p.player,group)}`} onFocus={()=>setActive(p.player.id)} onMouseEnter={()=>setActive(p.player.id)} onClick={()=>setActive(p.player.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setActive(p.player.id);}}}><circle cx={px(p.x.value)} cy={py(p.y.value)} r={13} fill="transparent"/>{active===p.player.id&&<circle cx={px(p.x.value)} cy={py(p.y.value)} r={10} className={styles.selection}/>}<Mark index={groups.indexOf(pointGroup(p.player,group))} cx={px(p.x.value)} cy={py(p.y.value)}/><title>{`${p.player.name} · ${pointGroup(p.player,group)} · X: ${reading(p.x)} (${p.x.date}) · Y: ${reading(p.y)} (${p.y.date})`}</title></g>)}
        </svg></div>
        <div className={styles.plotNote}><span>{fit?"Dashed line: best fit for all visible players":"Best-fit line requires 5 paired players and variation in X."}</span><span>Focused axes · No outliers removed</span></div>
        <div className={styles.selectionCard} aria-live="polite">{selected?<><Link href={`/athletes/${selected.player.id}`} className="font-bold underline underline-offset-2">{selected.player.name}</Link><span>{pointGroup(selected.player,group)}</span><span>{x?.label}: <b>{reading(selected.x)}</b> · {date(selected.x.date)}</span><span>{y?.label}: <b>{reading(selected.y)}</b> · {date(selected.y.date)}</span></>:<span>Hover, tap, or focus a dot to see the player, exact readings, and test dates.</span>}</div>
        {points.length<8&&<p className="muted text-sm mt-4">Small sample: {points.length} paired players. Treat this as an early view while more testing is added.</p>}
        {fit?.r===null&&<p className="muted text-sm mt-4">All Y values are identical, so Pearson r and R² are undefined.</p>}
      </>}
      <p className={styles.caution}>Correlation shows how two measurements vary together; it does not establish cause, a training target, or a health rating.</p>
    </section>
    <details className={`panel ${styles.details}`}><summary>Players &amp; Test Dates · {points.length} Plotted · {paired.excluded.length} Missing or Outside Date Gap{hidden.length?` · ${paired.points.length-points.length} Hidden by Color`:""}</summary><div className="table-wrap mt-4"><table><caption className="sr-only">Players and exact values used in the correlation</caption><thead><tr><th>Player</th><th>{x?.label??"X"}</th><th>X Date</th><th>{y?.label??"Y"}</th><th>Y Date</th><th>{COLOR_GROUPS.find(g=>g.key===group)?.label}</th></tr></thead><tbody>{points.map(p=><tr key={p.player.id}><th scope="row"><Link href={`/athletes/${p.player.id}`} className="underline underline-offset-2">{p.player.name}</Link></th><td>{p.x.value} {p.x.unit}</td><td>{p.x.date}</td><td>{p.y.value} {p.y.unit}</td><td>{p.y.date}</td><td>{pointGroup(p.player,group)}</td></tr>)}</tbody></table></div>{paired.excluded.length>0&&<div className="mt-5"><h3 className="text-sm font-bold">Not Plotted</h3><ul className={styles.excluded}>{paired.excluded.map(e=><li key={e.player.id}><Link href={`/athletes/${e.player.id}`} className="underline underline-offset-2">{e.player.name}</Link><span>{e.reason}</span></li>)}</ul></div>}</details>
    <details className={`panel ${styles.details}`}><summary>How to Read This Chart</summary><div className="muted mt-4 space-y-3 text-sm leading-6"><p>Each axis keeps its measurement, device/source, and original unit separate. The chart uses each player’s latest test for that combination in the selected period. Same-day repeats use the most recently imported reading, with observation ID as a stable tie-breaker. It does not search for older tests to fill excluded pairs.</p><p>Class and position come from the current active/redshirt 2026–27 roster. Position means primary position. Select legend groups to hide or show them; the line and correlation update using all visible dots, not separate lines per group.</p><p>Pearson r ranges from −1 to +1 and describes a linear relationship. R² is the square of r for this straight-line model. The least-squares line predicts Y from X only across the observed X range. These statistics require at least five pairs here; a small sample, outliers, or a curved pattern can make a straight-line summary misleading.</p><p>Body composition measures can be mathematically related within the same report. A strong correlation between related measurements may reflect their calculation rather than an independent performance relationship. Game-sheet cumulative totals are separate from these dated testing measurements.</p></div></details>
  </div>;
}
