import { GamePercentile } from "@/components/game-percentile";
import type { GameComparison } from "@/lib/game-metrics";
import { battingRates, formatBattingRate } from "@/lib/batting-stats";
import { StatInfo } from "@/components/stat-info";
import type { SharedGameStat } from "@/lib/game-server";
const labels:Record<string,string>={pa:"PA",qpa:"QPA",qpa_pct:"QPA %",ab:"AB",pitches:"Pitches",strikes:"Strikes",strike_pct:"Strike %",bb_outcome:"BB",h:"Hits",r:"Runs",k:"K",hbp:"HBP",fb:"FB",fb_k:"FB K",bb_pitch_family:"BB (pitch family)",bb_pitch_family_k:"BB K (pitch family)",ch:"CH",ch_k:"CH K",baf:"BAF",fps:"FPS",hh_base_hit:"HH Base Hit",hh_extra_base_hit:"HH Extra Base Hit",pumps:"HR",base_hit:"Hits",three_eight_hh:"3–8 HH",eight_plus_pitches:"8+ pitches",bb:"BB",rbi:"RBI",sac_bunt:"Sac Bunt",moving_runner:"Moving Runner",punchies:"Punchies",ab_control:"AB Control",sb:"SB",gdp:"GDP",sac_fly:"Sac Fly"};
const primaryQpa=["pumps","rbi","sb","gdp","base_hit","ab"];
const primaryPitching=["pitches","strike_pct","k","bb_outcome"];
const value=(row:SharedGameStat|undefined)=>row?(row.unit==="%"?`${row.value.toFixed(1)}%`:row.value):"—";
const updated=(rows:SharedGameStat[])=>new Date([...rows].sort((a,b)=>b.fetched_at.localeCompare(a.fetched_at))[0].fetched_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"America/Los_Angeles"});
const gameDate=(date:string|null)=>date?new Date(`${date}T12:00:00Z`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}):"Date unavailable";
function MetricGrid({rows,comparisons=[]}:{rows:SharedGameStat[];comparisons?:GameComparison[]}){return <dl className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-3">{rows.map(row=><div key={row.metric} className="rounded-xl border border-[var(--line-subtle)] bg-[var(--surface-raised)] p-3"><dt className="text-xs text-[var(--text-secondary)]">{labels[row.metric]??row.metric}<StatInfo metric={row.metric} label={labels[row.metric]??row.metric} /></dt><dd className="mt-2 text-3xl font-black tabular-nums">{value(row)}</dd><GamePercentile label={labels[row.metric]??row.metric} comparison={comparisons.find(c=>c.metric===row.metric&&c.source===row.source&&c.eventId===(row.event_id??"")&&c.snapshotId===row.snapshot_id&&c.value===row.value)}/></div>)}</dl>;}
export function AthleteGameStats({stats,comparisons=[]}:{stats:SharedGameStat[];comparisons?:GameComparison[]}) {
 const qpa=stats.filter(row=>row.source==="qpa_fall_2026"),pitching=stats.filter(row=>row.source==="pitching_fall_2026");
 const games=[...new Set(pitching.map(row=>row.event_id))].map(id=>pitching.filter(row=>row.event_id===id)).sort((a,b)=>(b[0].played_on??"").localeCompare(a[0].played_on??"")||(a[0].event_id??"").localeCompare(b[0].event_id??""));
 const rateOrder=["batting_avg","batting_obp","qpa_pct","batting_hh_pct","batting_bb_pct","batting_k_pct"];
 const rates=[...battingRates(qpa),...qpa.filter(r=>r.metric==="qpa_pct").map(r=>({metric:r.metric,label:"QPA %",value:r.value,unit:"%" as const}))].sort((a,b)=>rateOrder.indexOf(a.metric)-rateOrder.indexOf(b.metric));
 const otherQpa=qpa.filter(row=>!primaryQpa.includes(row.metric)&&row.metric!=="qpa_pct"),otherPitching=pitching.filter(row=>!primaryPitching.includes(row.metric));
 return <section className="panel mt-3 p-5 sm:p-6" aria-label="Fall 2026 game statistics">{!stats.length?<div className="py-6 text-center"><h2 className="mt-0 text-lg font-bold">Game Results Will Appear Here</h2><p className="muted mb-0 text-sm">No recorded Fall 2026 results yet. Results appear after the next verified team-sheet update.</p></div>:<>
  {qpa.length>0&&<div><h3 className="font-semibold">QPA · Fall Totals</h3><p className="muted text-xs">Updated {updated(qpa)} · Fall 2026</p>{rates.length>0&&<dl className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{rates.map(rate=><div key={rate.metric} className="rounded-xl border border-[var(--line-subtle)] bg-[var(--surface-raised)] p-4"><dt className="text-xs font-semibold text-[var(--text-secondary)]">{rate.label}<StatInfo metric={rate.metric} label={rate.label}/></dt><dd className="mt-2 text-3xl font-black tabular-nums">{formatBattingRate(rate)}</dd><GamePercentile label={rate.label} comparison={comparisons.find(c=>c.metric===rate.metric&&c.source==="qpa_fall_2026"&&c.snapshotId===qpa[0]?.snapshot_id&&Math.abs(c.value-rate.value)<1e-10)}/></div>)}</dl>}<MetricGrid comparisons={comparisons} rows={primaryQpa.flatMap(metric=>qpa.filter(row=>row.metric===metric))}/></div>}
  {games.length>0&&<div className="mt-6"><h3 className="font-semibold">Pitching · Game by Game</h3><p className="muted text-xs">Updated {updated(pitching)} · Strike % is strikes divided by pitches.</p><div className="table-wrap mt-3"><table aria-label="Pitching game statistics"><thead><tr><th>Date</th>{primaryPitching.map(metric=><th key={metric}>{labels[metric]}<StatInfo metric={metric} label={labels[metric]} /></th>)}</tr></thead><tbody>{games.map(game=><tr key={game[0].event_id}><td className="whitespace-nowrap">{gameDate(game[0].played_on)}</td>{primaryPitching.map(metric=><td key={metric}>{value(game.find(row=>row.metric===metric))}<GamePercentile label={labels[metric]} comparison={comparisons.find(c=>c.source==="pitching_fall_2026"&&c.eventId===game[0].event_id&&c.metric===metric&&c.snapshotId===game[0].snapshot_id)}/></td>)}</tr>)}</tbody></table></div></div>}
  {(otherQpa.length>0||otherPitching.length>0)&&<details className="mt-6"><summary className="cursor-pointer text-sm font-semibold">More Stats</summary>{otherQpa.length>0&&<div className="mt-4"><h3 className="mb-3 text-sm font-semibold">Additional QPA Totals</h3><MetricGrid comparisons={comparisons} rows={otherQpa}/></div>}{otherPitching.length>0&&<div className="table-wrap mt-4"><table aria-label="Additional pitching statistics"><thead><tr><th>Date</th><th>Metric</th><th>Recorded</th></tr></thead><tbody>{games.flatMap(game=>game.filter(row=>!primaryPitching.includes(row.metric)).sort((a,b)=>a.source_column-b.source_column).map(row=><tr key={`${row.event_id}:${row.metric}`}><td className="whitespace-nowrap">{gameDate(row.played_on)}</td><td>{labels[row.metric]??row.metric}<StatInfo metric={row.metric} label={labels[row.metric]??row.metric} /></td><td>{value(row)}</td></tr>))}</tbody></table></div>}</details>}
 <p className="muted mt-6 text-xs leading-5">Percentiles compare recorded Fall results with at least five eligible Pacific players. QPA uses the current cumulative snapshot; pitching compares the same game. Count rankings depend on opportunities. Blue is a lower percentile; red is higher. Lower K% and GDP improve batting rank; higher BB% improves batting rank.</p></>}</section>;
}
