import type { SharedGameStat } from "@/lib/game-server";
const labels:Record<string,string>={pa:"PA",qpa:"QPA",qpa_pct:"QPA %",ab:"AB",pitches:"Pitches",strikes:"Strikes",strike_pct:"Strike %",bb_outcome:"BB",h:"Hits",r:"Runs",k:"K",hbp:"HBP",fb:"FB",fb_k:"FB K",bb_pitch_family:"BB (pitch family)",bb_pitch_family_k:"BB K (pitch family)",ch:"CH",ch_k:"CH K",baf:"BAF",fps:"FPS",hh_base_hit:"HH Base Hit",hh_extra_base_hit:"HH Extra Base Hit",pumps:"Pumps",base_hit:"Base Hit",three_eight_hh:"3–8 HH",eight_plus_pitches:"8+ pitches",bb:"BB",rbi:"RBI",sac_bunt:"Sac Bunt",moving_runner:"Moving Runner",punchies:"Punchies",ab_control:"AB Control"};
const primaryQpa=["pa","qpa","qpa_pct","ab","bb","rbi"];
const primaryPitching=["pitches","strike_pct","k","bb_outcome"];
const value=(row:SharedGameStat|undefined)=>row?(row.unit==="%"?`${row.value.toFixed(1)}%`:row.value):"—";
const updated=(rows:SharedGameStat[])=>new Date([...rows].sort((a,b)=>b.fetched_at.localeCompare(a.fetched_at))[0].fetched_at).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles"});
function MetricGrid({rows}:{rows:SharedGameStat[]}){return <dl className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{rows.map(row=><div key={row.metric} className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">{labels[row.metric]??row.metric}</dt><dd className="mt-1 text-lg font-bold">{value(row)}</dd></div>)}</dl>;}
export function AthleteGameStats({stats}:{stats:SharedGameStat[]}) {
 const qpa=stats.filter(row=>row.source==="qpa_fall_2026"),pitching=stats.filter(row=>row.source==="pitching_fall_2026");
 const games=[...new Set(pitching.map(row=>row.event_id))].map(id=>pitching.filter(row=>row.event_id===id)).sort((a,b)=>(b[0].played_on??"").localeCompare(a[0].played_on??"")||(a[0].event_id??"").localeCompare(b[0].event_id??""));
 const otherQpa=qpa.filter(row=>!primaryQpa.includes(row.metric)),otherPitching=pitching.filter(row=>!primaryPitching.includes(row.metric));
 return <section className="panel mt-6 p-5 sm:p-6"><p className="eyebrow text-pacu-red">Fall 2026</p><h2 className="mt-2 text-xl font-bold">Game Stats</h2>{!stats.length?<p className="muted mb-0">No recorded game statistics yet. Daily checks start September 12.</p>:<>
  {qpa.length>0&&<div className="mt-5"><h3 className="font-semibold">QPA · Fall Totals</h3><p className="muted text-xs">Updated {updated(qpa)} · Blank entries are unavailable.</p><MetricGrid rows={primaryQpa.flatMap(metric=>qpa.filter(row=>row.metric===metric))}/></div>}
  {games.length>0&&<div className="mt-6"><h3 className="font-semibold">Pitching · Game by Game</h3><p className="muted text-xs">Updated {updated(pitching)} · Strike % is strikes divided by pitches.</p><div className="table-wrap mt-3"><table aria-label="Pitching game statistics"><thead><tr><th>Date</th>{primaryPitching.map(metric=><th key={metric}>{labels[metric]}</th>)}</tr></thead><tbody>{games.map(game=><tr key={game[0].event_id}><td>{game[0].played_on}</td>{primaryPitching.map(metric=><td key={metric}>{value(game.find(row=>row.metric===metric))}</td>)}</tr>)}</tbody></table></div></div>}
  {(otherQpa.length>0||otherPitching.length>0)&&<details className="mt-6"><summary className="cursor-pointer text-sm font-semibold">More Stats</summary>{otherQpa.length>0&&<div className="mt-4"><h3 className="mb-3 text-sm font-semibold">Additional QPA Totals</h3><MetricGrid rows={otherQpa}/></div>}{otherPitching.length>0&&<div className="table-wrap mt-4"><table aria-label="Additional pitching statistics"><thead><tr><th>Date</th><th>Metric</th><th>Recorded</th></tr></thead><tbody>{games.flatMap(game=>game.filter(row=>!primaryPitching.includes(row.metric)).sort((a,b)=>a.source_column-b.source_column).map(row=><tr key={`${row.event_id}:${row.metric}`}><td>{row.played_on}</td><td>{labels[row.metric]??row.metric}</td><td>{value(row)}</td></tr>))}</tbody></table></div>}</details>}
 </>}</section>;
}
