"use client";
import {startTransition,useRef,useState} from "react";
import Link from "next/link";
import {BULK_INVITE_LABELS,type BulkInvitePlayer,type BulkInviteOutcome} from "@/lib/bulk-invitations";
import {sendBulkPlayerInvite,prepareRejectedPlayerInvite} from "@/app/(workspace)/admin/access/bulk/actions";
export function BulkInviteForm({players}:{players:BulkInvitePlayer[]}){
 const ready=players.filter(p=>p.status==="ready"),excluded=players.filter(p=>p.status!=="ready");
 const [selected,setSelected]=useState(()=>new Set(ready.map(p=>p.id))),[confirmed,setConfirmed]=useState(false),[running,setRunning]=useState(false),[results,setResults]=useState<Record<string,BulkInviteOutcome>>({}),[message,setMessage]=useState("");
 const lock=useRef(false),stop=useRef(false);
 const needsReview=Object.values(results).some(result=>["review","limited"].includes(result.status));
 const pending=ready.filter(p=>selected.has(p.id)&&!results[p.id]);
 async function send(){if(lock.current||needsReview||!confirmed||!pending.length)return;lock.current=true;stop.current=false;setRunning(true);setMessage("");const queue=[...pending];let sent=0,skipped=0;
  try{for(const player of queue){if(stop.current){setMessage("Paused. The current invitation has finished; remaining players have not been sent.");break;}let result:BulkInviteOutcome;try{result=await sendBulkPlayerInvite(player.id,player.email,true);}catch{result={status:"review",message:"Connection interrupted. Check invitation history before trying again."};}setResults(previous=>({...previous,[player.id]:result}));if(["review","limited"].includes(result.status)){setMessage(result.status==="limited"?result.message:"Batch paused for review. No later invitations were attempted. Refresh after reviewing this account to continue with unsent players.");break;}if(result.status==="sent")sent++;else skipped++;setMessage(`${sent} sent · ${skipped} skipped in this batch.`);}}
  finally{lock.current=false;setRunning(false);setConfirmed(false);}
 }
 return <div className="space-y-5"><div className="grid grid-cols-2 gap-3"><div className="panel p-5"><p className="muted m-0 text-sm">Ready for invitation</p><p className="mb-0 mt-2 text-3xl font-bold">{ready.length}</p></div><div className="panel p-5"><p className="muted m-0 text-sm">Excluded / Already Connected</p><p className="mb-0 mt-2 text-3xl font-bold">{excluded.length}</p></div></div>
 <section className="panel p-4 sm:p-6" aria-labelledby="bulk-review-heading"><h2 id="bulk-review-heading" className="mt-0 text-lg font-bold">Review Recipients</h2><p className="muted text-sm">Each selected player receives an individual email to choose a password, with Player access linked only to the profile shown. Existing sign-ins and linked accounts are excluded.</p>
 <label className="mb-4 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={pending.length>0&&ready.filter(p=>!results[p.id]).every(p=>selected.has(p.id))} disabled={running||!ready.some(p=>!results[p.id])} onChange={e=>{setSelected(new Set(e.target.checked?ready.filter(p=>!results[p.id]).map(p=>p.id):[]));setConfirmed(false);}}/>Select all remaining players</label>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th scope="col">Send</th><th scope="col">Player</th><th scope="col">Roster Email</th><th scope="col">Status</th></tr></thead><tbody>{ready.map(p=><tr key={p.id}><td><input type="checkbox" aria-label={`Invite ${p.name}`} checked={selected.has(p.id)} disabled={running||!!results[p.id]} onChange={e=>{setSelected(old=>{const next=new Set(old);if(e.target.checked)next.add(p.id);else next.delete(p.id);return next;});setConfirmed(false);}}/></td><td><Link href={`/athletes/${p.id}`} className="font-semibold text-link">{p.name}</Link><span className="muted mt-1 block text-xs">{p.code}</span></td><td className="break-all">{p.email}</td><td className="min-w-40 text-xs">{results[p.id]?.message??"Ready · Player access"}</td></tr>)}</tbody></table></div>{!ready.length&&<p className="notice">No new player invitations are ready. Review the excluded accounts below.</p>}
 </section>
 <section className="panel space-y-4 p-5"><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} disabled={running||needsReview||!pending.length} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed the selected players, their roster emails, and their profile matches. I approve sending these invitations and granting Player access.</span></label><div className="flex flex-wrap items-center gap-3"><button type="button" className="btn btn-primary" disabled={running||needsReview||!confirmed||!pending.length} onClick={()=>startTransition(send)}>{running?"Sending Invitations…":`Send ${pending.length} Invitation${pending.length===1?"":"s"}`}</button>{running&&<button type="button" className="btn btn-secondary" onClick={()=>{stop.current=true;setMessage("Pausing after the current invitation finishes…");}}>Pause</button>}</div><p className="muted m-0 text-xs">Keep this page open while sending. A delivery or account-setup issue pauses the batch. Previously attempted invitations are never resent automatically.</p>{message&&<p role="status" className="notice m-0">{message}</p>}</section>
 {excluded.length>0&&<details className="panel p-5"><summary className="cursor-pointer font-semibold">Excluded Players · {excluded.length}</summary><ul className="m-0 mt-4 list-none divide-y divide-[var(--line-subtle)] p-0">{excluded.map(p=><li key={p.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><Link href={`/athletes/${p.id}`} className="text-link">{p.name}</Link><span className="muted">{BULK_INVITE_LABELS[p.status]}</span>{p.status==="review"&&p.attemptId&&<RejectedInviteReview player={p}/>}</li>)}</ul></details>}
 </div>;
}

function RejectedInviteReview({player}:{player:BulkInvitePlayer}){
 const [checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState("");
 async function prepare(){if(!checked||busy||done||!player.attemptedEmail)return;setBusy(true);try{const result=await prepareRejectedPlayerInvite(player.attemptId!,player.id,player.attemptedEmail,true);setMessage(result.message);setDone(result.ok);}catch{setMessage("Could not verify this invitation. Nothing was resent.");}finally{setBusy(false);}}
 return <div className="w-full space-y-2 rounded-lg border border-[var(--line-subtle)] p-3"><p className="m-0 break-all text-xs">Original attempted email: {player.attemptedEmail??"Could not be verified"}{player.attemptedEmail&&player.attemptedEmail!==player.email&&<><br/>Current roster email: {player.email}. A new invitation will use this address after review.</>}</p><label className="flex items-start gap-2"><input type="checkbox" disabled={busy||done||!player.attemptedEmail} checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>I verified that the email provider rejected the original invitation before sending. Do not use for a timeout or uncertain delivery.</span></label><button type="button" className="btn btn-secondary" disabled={!checked||busy||done||!player.attemptedEmail} onClick={()=>startTransition(prepare)}>{done?"Ready After Refresh":busy?"Checking…":"Return to Invitation List"}</button>{message&&<p role="status" className="m-0 text-xs">{message}</p>}</div>;
}
