"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, ListOrdered, Info } from "lucide-react";
import { draftPlanning, draftRoster, draftOpenPositions, placeDraftPlayer, validateDraftDocument, FIELD_POSITIONS, type DraftDocument, type FieldPosition, type DraftPlanning } from "@/lib/draft-board";
import { performanceDraftOrder, type DraftPerformance, type DraftPerformanceLine } from "@/lib/draft-performance";
import styles from "./draft-planning.module.css";
type Save = (next:DraftDocument)=>void;
const coords:Record<FieldPosition,[number,number]>={LF:[16,18],CF:[50,9],RF:[84,18],SS:[33,42],"2B":[67,42],"3B":[15,60],"1B":[85,60],P:[50,59],C:[50,86],DH:[88,88]};
export function DraftDepthChart({document:doc,team,disabled,onSave}:{document:DraftDocument;team:0|1;disabled:boolean;onSave:Save}){
  const [position,setPosition]=useState<FieldPosition>("P"),[player,setPlayer]=useState("");
  const roster=draftRoster(doc,team),plan=draftPlanning(doc),assignments=plan.placements[team];
  const depth=assignments.filter(p=>p.position===position),unassigned=roster.filter(p=>!assignments.some(a=>a.playerId===p.id));
  function reorder(index:number,delta:number){const next=[...depth];[next[index],next[index+delta]]=[next[index+delta],next[index]];const placements=[...plan.placements] as DraftPlanning["placements"];placements[team]=[...assignments.filter(p=>p.position!==position),...next];onSave({...doc,planning:{...plan,placements}});}
  return <div className={styles.depth}>
    <div className={styles.field} role="group" aria-label={`${doc.teams[team].name} field depth chart`}>
      <svg viewBox="0 0 300 300" aria-hidden="true"><path d="M150 274 L16 132 Q8 20 150 12 Q292 20 284 132 Z" fill="currentColor" opacity=".09"/><path d="M150 260 L54 164 L150 68 L246 164 Z" fill="#b28b5b" opacity=".22"/><path d="M150 260 L36 145 M150 260 L264 145" fill="none" stroke="currentColor" opacity=".25"/><path d="M150 260 L68 178 L150 96 L232 178 Z" fill="none" stroke="currentColor" opacity=".35"/><circle cx="150" cy="178" r="8" fill="currentColor" opacity=".18"/></svg>
      {FIELD_POSITIONS.map(pos=>{const players=assignments.filter(p=>p.position===pos),starter=roster.find(p=>p.id===players[0]?.playerId);return <button type="button" key={pos} className={styles.spot} style={{left:`${coords[pos][0]}%`,top:`${coords[pos][1]}%`}} aria-label={`${pos}: ${starter?.name??"Open"}${players.length>1?`, ${players.length-1} backups`:""}`} aria-pressed={position===pos} onClick={()=>{setPosition(pos);setPlayer("");}}><b>{pos}</b><span>{starter?starter.name.split(" ").slice(-1).join(" "):"Open"}</span>{players.length>1&&<small>+{players.length-1}</small>}</button>;})}
    </div>
    <div className={styles.editDepth}><div className={styles.depthTitle}><strong>{position} Depth</strong><span>{depth.length} assigned</span></div>
      {depth.length?<ol>{depth.map((p,index)=><li key={p.playerId}><div><small>{index===0?"Starter":`Backup ${index}`}</small><strong>{roster.find(r=>r.id===p.playerId)?.name}</strong></div><div className={styles.miniActions}><button disabled={disabled||index===0} aria-label={`Move ${roster.find(r=>r.id===p.playerId)?.name} up at ${position}`} onClick={()=>reorder(index,-1)}><ArrowUp size={14}/></button><button disabled={disabled||index===depth.length-1} aria-label={`Move ${roster.find(r=>r.id===p.playerId)?.name} down at ${position}`} onClick={()=>reorder(index,1)}><ArrowDown size={14}/></button><button disabled={disabled} aria-label={`Unassign ${roster.find(r=>r.id===p.playerId)?.name}`} onClick={()=>onSave(placeDraftPlayer(doc,team,p.playerId,null,position))}>×</button></div></li>)}</ol>:<p className={styles.empty}>Choose a drafted player or captain for this spot.</p>}
      <div className={styles.assign}><label><span className="sr-only">{doc.teams[team].name} player for {position}</span><select value={player} disabled={disabled} onChange={e=>setPlayer(e.target.value)}><option value="">Choose a player</option>{roster.filter(r=>!depth.some(p=>p.playerId===r.id)).map(r=><option key={r.id} value={r.id}>{r.name}{assignments.find(a=>a.playerId===r.id)?` · also ${assignments.filter(a=>a.playerId===r.id).map(a=>a.position).join("/")}`:""}</option>)}</select></label><button type="button" disabled={disabled||!roster.some(r=>r.id===player)} onClick={()=>{onSave(placeDraftPlayer(doc,team,player,position));setPlayer("");}}>Assign</button></div>
      <p className={styles.notes}>{unassigned.length} unassigned · {draftOpenPositions(doc,team).length} field spots open. Click a field spot to set its depth. Two-way and utility players can appear at multiple spots. P depth is your pitching staff; the first name starts.</p>
    </div>
  </div>;
}
function Evidence({line,label}:{line:DraftPerformanceLine|null|undefined;label:string}){
  return <div className={styles.evidence}><small>{label}</small>{line?.score!==null&&line?.score!==undefined?<><b>{line.score.toFixed(1)}<small>/100</small></b><div className={styles.track}><i style={{width:`${line.score}%`}}/></div></>:<span>Unranked</span>}{line&&<details><summary>{line.early?"Early sample · Stats":"View stats & sample"}</summary>{line.stats.map(s=><p key={s.label}><strong>{s.label} {s.value}</strong><small>{s.sample||"Sample unavailable"}</small></p>)}<small>Sheet changed {new Date(line.updatedAt).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles"})}</small></details>}</div>;
}
export function DraftBigBoard({document:doc,performance,disabled,onSave,onError}:{document:DraftDocument;performance:DraftPerformance[]|null;disabled:boolean;onSave:Save;onError:(s:string)=>void}){
  const [order,setOrder]=useState(draftPlanning(doc).bigBoard),[players,setPlayers]=useState(doc.players),[search,setSearch]=useState("");
  const [changed,setChanged]=useState(false);
  function move(id:string,to:number){const from=order.indexOf(id);if(from<0||!Number.isInteger(to)||to<0||to>=order.length)return;const next=order.filter(p=>p!==id);next.splice(to,0,id);setOrder(next);setChanged(true);}
  function suggest(discipline:"hitting"|"pitching"){setOrder(performanceDraftOrder({...doc,players,planning:{...draftPlanning(doc),bigBoard:order}},performance??[],discipline));setChanged(true);}
  return <section className={styles.bigBoard} aria-label="Private big board"><header><div><p>YOUR PRE-DRAFT RANKINGS</p><h3><ListOrdered size={20}/>Big Board</h3></div><button className="btn btn-primary" disabled={disabled||!changed} onClick={()=>{try{onSave(validateDraftDocument({...doc,players,planning:{...draftPlanning(doc),bigBoard:order}}));}catch(e){onError(e instanceof Error?e.message:"Check the board.");}}}>Save Big Board</button></header>
    <div className={styles.boardControls}><label><span className="sr-only">Search big board</span><input placeholder="Search players or positions" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn btn-secondary" disabled={disabled||!performance} onClick={()=>{setPlayers(players.map(p=>{if(p.athleteId)return p;const exact=performance?.filter(r=>r.name.toLowerCase()===p.name.toLowerCase());return exact?.length===1?{...p,athleteId:exact[0].id}:p;}));setChanged(true);}}>Preview Exact Name Matches</button><button className="btn btn-secondary" disabled={disabled||!performance} onClick={()=>suggest("hitting")}>Suggest Hitter Order</button><button className="btn btn-secondary" disabled={disabled||!performance} onClick={()=>suggest("pitching")}>Suggest Pitcher Order</button></div>
    {performance===null&&<p className="notice">Performance suggestions are temporarily unavailable. Your rankings and draft progress are safe.</p>}
    <details className={styles.method}><summary><Info size={14}/>How suggestions work</summary><p>Preview Exact Name Matches proposes only a unique full-name match. Review every selected profile before saving; nicknames and unmatched names need the dropdown. Match a draft name to an existing profile to use its logged stats. Matches affect this private draft only. Suggest Hitter/Pitcher Order sorts by the existing Top Performers score; it previews an order until you save. Two-way players retain separate hitting and pitching scores. Missing results stay unranked and keep their relative order.</p><p>Hitting: PAC Production+, QPA%, OBP and ISO, equally weighted. Pitching: WHIP, K/BB and Runs/9, equally weighted. These are Fall game-stat team-percentile blends, requiring five complete comparable lines. Early samples remain included. ISO treats combined doubles/triples as doubles. A high score is a team comparison, not a talent prediction. Open-position suggestions use your field assignments and broad sheet groups; unassigned players may already cover those needs.</p></details>
    <div className={styles.boardRows}>{order.filter(id=>{const p=players.find(p=>p.id===id)!;return `${p.name} ${p.group} ${p.positions}`.toLowerCase().includes(search.toLowerCase().trim());}).map(id=>{const player=players.find(p=>p.id===id)!,index=order.indexOf(id),profile=performance?.find(p=>p.id===player.athleteId),picked=doc.picks.includes(id);return <article key={id} className={styles.boardRow} data-picked={picked}>
      <div className={styles.rank}><label><span className="sr-only">Rank for {player.name}</span><input key={`${id}-${index}`} type="number" min={1} max={order.length} defaultValue={index+1} disabled={disabled} onBlur={e=>move(id,Number(e.target.value)-1)} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/></label><div className={styles.miniActions}><button disabled={disabled||index===0} aria-label={`Move ${player.name} up the big board`} onClick={()=>move(id,index-1)}><ArrowUp size={14}/></button><button disabled={disabled||index===order.length-1} aria-label={`Move ${player.name} down the big board`} onClick={()=>move(id,index+1)}><ArrowDown size={14}/></button></div></div>
      <div className={styles.boardPlayer}><strong>{player.name}{picked&&<span>Drafted</span>}</strong><small>{player.group}{player.positions?` · ${player.positions}`:""}</small><label><span className="sr-only">Dashboard profile for {player.name}</span><select disabled={disabled||!performance} value={player.athleteId??""} onChange={e=>{setPlayers(players.map(p=>p.id===id?{...p,athleteId:e.target.value||null}:p));setChanged(true);}}><option value="">Match dashboard profile</option>{performance?.map(p=><option key={p.id} value={p.id}>{p.name} · {p.position||"Position pending"}</option>)}</select></label>{profile&&<small>Matched: {profile.name}</small>}</div>
      <Evidence label="Hitting" line={profile?.hitting}/><Evidence label="Pitching" line={profile?.pitching}/>
    </article>;})}</div><p className={styles.notes}>{changed?"Unsaved changes — check the selected profiles and ranks, then save your big board before drafting.":"Your saved order follows the players as they are drafted. Change a rank or use the arrows to reorder."}</p>
  </section>;
}
