import { GameOpportunity } from "@/components/game-opportunity";
import Link from "next/link";
import { StatInfo } from "@/components/stat-info";
import { LeaderboardNavigation } from "@/components/leaderboard-navigation";
import { GAME_LEADERBOARD_METRICS, GAME_METRIC_LABELS, gameDirection, gameValue, type GameLeaderboardRow } from "@/lib/game-metrics";
import { leaderboardTestDate } from "@/lib/leaderboards";
import styles from "./leaderboard.module.css";
const labels:Record<string,string>={...GAME_METRIC_LABELS,strike_pct:"Strike %",k:"Strikeouts",bb_outcome:"Walks Allowed",pitches:"Pitches"};
function Rows({rows,label}:{rows:GameLeaderboardRow[];label:string}){return <div className={styles.tableWrap}><table  aria-label={`${label} game rankings`}><thead><tr><th scope="col">Rank</th><th scope="col">Player</th><th scope="col">{label}</th></tr></thead><tbody>{rows.map(r=><tr key={r.code}><td className={styles.rank}>{r.rank}</td><th scope="row"><span className={styles.player}>{r.profileId?<Link href={`/athletes/${r.profileId}`} prefetch={false}>{r.name}</Link>:r.name}</span><span className={styles.playerMeta}>{r.code}</span></th><td className={styles.result}>{gameValue(r.value,r.unit)}<GameOpportunity source={r.source} metric={r.metric} count={r.opportunities}/></td></tr>)}</tbody></table></div>;}
export function GameLeaderboard({rows}:{rows:GameLeaderboardRow[]}){
 const groups=new Map<string,GameLeaderboardRow[]>();for(const row of rows){const key=JSON.stringify([row.source,row.eventId,row.metric]);groups.set(key,[...(groups.get(key)??[]),row]);}
 const panels=[...groups.values()].sort((a,b)=>a[0].source.localeCompare(b[0].source)||a[0].eventId.localeCompare(b[0].eventId)||(GAME_LEADERBOARD_METRICS as readonly string[]).indexOf(a[0].metric)-(GAME_LEADERBOARD_METRICS as readonly string[]).indexOf(b[0].metric));
 return <><LeaderboardNavigation group="games"/>{!panels.length?<section className="panel p-8 text-center"><h2 className="text-xl font-bold">Game Rankings Are Coming</h2><p className="muted text-sm">Recorded Fall game results will appear here after the next verified sheet update.</p></section>:<div className="leaderboard-grid">{panels.map(group=>{const first=group[0],label=labels[first.metric]??first.metric,sorted=[...group].sort((a,b)=>a.rank-b.rank||a.code.localeCompare(b.code)),direction=gameDirection(first.source,first.metric);return <section className={`panel ${styles.card}`} key={JSON.stringify([first.source,first.eventId,first.metric])}><header className="border-b border-[var(--line-subtle)] p-5"><p className="eyebrow mb-2 text-[var(--accent-readable)]">{first.source==="qpa_fall_2026"?"QPA · Fall 2026":`Pitching · ${leaderboardTestDate(first.playedOn!)}`}</p><h2 className="m-0 text-xl font-extrabold">{label}<StatInfo metric={first.metric} label={label}/></h2><p className="muted mb-0 mt-2 text-xs">{direction==="lower"?"Lowest first":"Highest first"} · {group.length} players · Updated {new Date(first.updatedAt).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"America/Los_Angeles"})}</p></header><Rows rows={sorted.slice(0,5)} label={label}/>{sorted.length>5&&<details className="border-t border-[var(--line-subtle)]"><summary className="cursor-pointer px-5 py-4 text-sm font-semibold">All {sorted.length} Players</summary><Rows rows={sorted.slice(5)} label={`${label} remaining`}/></details>}</section>;})}</div>}<details className="mt-6 text-xs text-[var(--text-secondary)]"><summary className="cursor-pointer font-semibold">About Game Rankings</summary><div className="mt-3 max-w-3xl space-y-2 leading-6"><p>QPA rankings use the latest cumulative Fall snapshot. Pitching rankings compare the same recorded game. Equal values share places (1, 1, 3). Opportunity counts sit beneath each result: AVG uses AB, OBP uses AB + BB + HBP + SF, HH% uses the team’s AB − K − Sac Bunt denominator, and the other batting rates use PA. PA beneath HR, SB or GDP is playing-time context, not a success-rate denominator. Pitching Strike % uses pitches. These counts differ from the number of teammates in a percentile cohort. “Limited sample” is a dashboard display label below 20 batting opportunities or 50 pitches; it is not a qualification cutoff. All recorded opportunities are included; no minimum PA cutoff is applied yet.</p><p>AVG and OBP display three decimals; rankings use the unrounded values. Higher batting BB% is better; lower batting K% and GDP are better. Counts depend on playing opportunities. HH% follows the QPA sheet formula shown in its info button.</p><p>These rankings are visible to signed-in players and staff. A player’s full game history and profile remain limited to that player and staff.</p></div></details></>;
}
