"use client";
import Link from "next/link";
import {useRef,useState} from "react";
import {saveGameLog} from "@/app/(workspace)/game-stats/log/actions";
import {BATTING_FIELDS,PITCHING_FIELDS,validateGameLog,type GameCounts,type GameLog,type GameLogInput,type GameLogSaveResult} from "@/lib/game-log";
type Athlete={id:string;name:string;athleteCode:string};
export function GameLogEntry({athletes,today,initial,saveAction=saveGameLog}:{athletes:Athlete[];today:string;initial?:GameLog;saveAction?:(input:unknown,confirmed:boolean)=>Promise<GameLogSaveResult>}){
 const [athleteId,setAthleteId]=useState(initial?.athleteId??""),[date,setDate]=useState(initial?.playedOn??today),[opponent,setOpponent]=useState(initial?.opponent??""),[number,setNumber]=useState(initial?.gameNumber??1),[kind,setKind]=useState<"game"|"intrasquad">(initial?.kind??"game");
 const [batting,setBatting]=useState<Record<string,string>>(Object.fromEntries(Object.entries(initial?.batting??{}).map(([k,v])=>[k,String(v)]))),[pitching,setPitching]=useState<Record<string,string>>(Object.fromEntries(Object.entries(initial?.pitching??{}).map(([k,v])=>[k,String(v)])));
 const [review,setReview]=useState<GameLogInput|null>(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<GameLogSaveResult|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[attempted,setAttempted]=useState(false);
 const lock=useRef(false),request=useRef<string|null>(null),record=useRef<string|null>(initial?.id??null);
 function invalidate(){if(attempted)return;setReview(null);setConfirmed(false);setResult(null);setError("");}
 function counts(fields:Record<string,string>):GameCounts{const out:GameCounts={};for(const [k,v]of Object.entries(fields)){if(v.trim()==="")continue;if(!/^\d+$/.test(v))throw Error("Enter whole counts, or leave unknown counts blank.");out[k]=Number(v);}return out;}
 function prepare(){if(attempted)return;setError("");try{request.current??=crypto.randomUUID();record.current??=crypto.randomUUID();setReview(validateGameLog({requestId:request.current,id:record.current,expectedVersion:initial?.version??0,athleteId,playedOn:date,opponent,gameNumber:number,kind,batting:counts(batting),pitching:counts(pitching)},today));setConfirmed(false);}catch(e){setError(e instanceof Error?e.message:"Review the counts.");}}
 async function save(){if(lock.current||!review||!confirmed||result?.status==="saved")return;lock.current=true;setBusy(true);setAttempted(true);try{const r=await saveAction(review,true);if(r.status==="saved"&&(r.id!==review.id||r.version!==review.expectedVersion+1))throw Error("Invalid receipt");setResult(r);if(r.status==="invalid")setAttempted(false);}catch{setResult({status:"uncertain",error:"Save could not be confirmed. Check the game log or retry this same entry."});}finally{lock.current=false;setBusy(false);}}
 const name=athletes.find(a=>a.id===athleteId)?.name??"Player";
 return <div className="space-y-5"><form className="panel p-5 sm:p-7" onSubmit={e=>{e.preventDefault();prepare();}}><fieldset disabled={busy||attempted} className="space-y-6"><div className="grid gap-4 sm:grid-cols-2">
 <label>Player<select value={athleteId} disabled={!!initial} onChange={e=>{invalidate();setAthleteId(e.target.value);}} required><option value="">Choose player</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.name} · {a.athleteCode}</option>)}</select></label>
 <label>Game Date<input type="date" min="2026-09-01" max={today<"2026-12-31"?today:"2026-12-31"} value={date} required onChange={e=>{invalidate();setDate(e.target.value);}}/></label>
 <label>Opponent / Teams<input value={opponent} maxLength={80} placeholder="Opponent or intrasquad teams" required onChange={e=>{invalidate();setOpponent(e.target.value);}}/></label>
 <div className="grid grid-cols-2 gap-3"><label>Type<select value={kind} onChange={e=>{invalidate();setKind(e.target.value as typeof kind);}}><option value="game">Game</option><option value="intrasquad">Intrasquad</option></select></label><label>Game Number<select value={number} onChange={e=>{invalidate();setNumber(Number(e.target.value));}}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div></div>
 <p className="muted text-sm">Enter 0 when none were recorded. Leave unknown counts blank. Add only this game’s results.</p>
 {([["Batting",BATTING_FIELDS,batting,setBatting],["Pitching",PITCHING_FIELDS,pitching,setPitching]] as const).map(([title,fields,values,setter])=><details key={title} open={title==="Batting"? !initial||!!Object.keys(initial.batting).length:!!Object.keys(initial?.pitching??{}).length} className="rounded-xl border border-[var(--line-subtle)] p-4"><summary className="cursor-pointer font-bold">{title}</summary><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{Object.entries(fields).map(([key,label])=><label key={key} className="text-xs">{label}<input aria-label={`${title} ${label}`} inputMode="numeric" type="number" min={0} max={1000} step={1} value={values[key]??""} onChange={e=>{invalidate();setter(current=>({...current,[key]:e.target.value}));}}/></label>)}</div></details>)}
 <button className="btn btn-primary" type="submit">Review Game Result</button></fieldset>{error&&<p role="alert" className="notice notice-error mt-4">{error}</p>}</form>
 {review&&<section className="panel p-5 sm:p-7" aria-label="Review game result"><h2 className="text-lg font-bold">Review {initial?"Correction":"Game Result"}</h2><p className="font-semibold">{name} · {review.playedOn} · {review.opponent} · Game {review.gameNumber}</p><p className="muted text-xs">{review.kind==="intrasquad"?"Intrasquad":"Game"} · Coach-entered result</p>
 {([["Batting",BATTING_FIELDS,review.batting],["Pitching",PITCHING_FIELDS,review.pitching]] as const).filter(([, ,v])=>Object.keys(v).length).map(([title,fields,v])=><div key={title} className="mt-4"><h3 className="text-sm font-bold">{title}</h3><dl className="mt-2 grid grid-cols-3 gap-3 sm:grid-cols-5">{Object.entries(v).map(([key,n])=><div key={key}><dt className="muted text-xs">{(fields as Record<string,string>)[key]}</dt><dd className="font-bold tabular-nums">{n}</dd></div>)}</dl></div>)}
 {result?.status!=="saved"&&<><label className="mt-5 flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>I checked the player, game date, opponent, and all recorded counts.</label><button className="btn btn-primary mt-4" disabled={!confirmed||busy} onClick={()=>void save()}>{busy?"Saving…":result?.status==="uncertain"?"Retry Same Entry":"Save Game Result"}</button></>}
 {result?.status==="saved"?<div className="notice notice-success mt-4" role="status">Game result saved.<div className="mt-3 flex flex-wrap gap-3"><Link href={`/athletes/${athleteId}`} className="text-link">Player Profile</Link><Link href="/game-stats/log" className="text-link">Game Log</Link><a href="/game-stats/log?new=1" className="text-link">Add Another Result</a></div></div>:result&&<p role="alert" className="notice mt-4">{result.error}</p>}
 </section>}</div>;
}
