"use client";
import { useMemo,useRef,useState } from "react";
import { useFormStatus } from "react-dom";
import { parseGameSource,type GameSourceSnapshot,type ReviewedGameIdentity,type ReviewedPitchingEvent } from "@/lib/game-source";
import { GAME_SOURCES,GAME_SOURCE_LABELS } from "@/lib/game-source-config";
import { validateGameImport } from "@/lib/game-import";
import { SubmitButton } from "@/components/submit-button";
type Choice={code:string;name:string};
type Bundle={snapshot:GameSourceSnapshot;identities?:ReviewedGameIdentity[];events?:ReviewedPitchingEvent[]};
const normalized=(text:string)=>text.trim().replace(/\s+/g," ").toLowerCase();
const blocks=[[39,40,70],[75,76,106],[112,113,143],[149,150,180],[186,187,217]] as const;
function Fields({athletes}:{athletes:Choice[]}){
 const {pending}=useFormStatus(),generation=useRef(0);
 const [bundle,setBundle]=useState<Bundle|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[approved,setApproved]=useState(false),[mappingApproved,setMappingApproved]=useState(false),[identities,setIdentities]=useState<ReviewedGameIdentity[]>([]),[events,setEvents]=useState<ReviewedPitchingEvent[]>([]),[limit,setLimit]=useState(100);
 async function read(file?:File){const version=++generation.current;setBundle(null);setApproved(false);setMappingApproved(false);setError(null);setLimit(100);if(!file)return;setBusy(true);
  try{if(file.size>5*1024*1024)throw new Error("Choose a prepared game snapshot no larger than 5 MiB.");const parsed=JSON.parse(await file.text());const next:Bundle=parsed.snapshot?parsed:{snapshot:parsed};if(!next.snapshot||!Object.hasOwn(GAME_SOURCES,next.snapshot.source)||!Array.isArray(next.snapshot.cells))throw new Error("Choose a prepared snapshot from one of the two approved Fall tabs.");
   const contract=GAME_SOURCES[next.snapshot.source],names=[...new Set(next.snapshot.cells.filter(cell=>cell.column===1&&contract.detailRows.includes(cell.row)&&typeof cell.entered==="string").map(cell=>cell.entered as string).filter(name=>name.trim()))];
   const choices=names.map(sourceName=>{const saved=next.identities?.find(m=>normalized(m.sourceName)===normalized(sourceName));const exact=athletes.filter(a=>normalized(a.name)===normalized(sourceName));return{sourceName,athleteCode:saved?.athleteCode??(exact.length===1?exact[0].code:"")};});
   if(version!==generation.current)return;setIdentities(choices);setEvents(blocks.map(([headerRow,firstRow,lastRow])=>next.events?.find(event=>event.headerRow===headerRow)??{headerRow,firstRow,lastRow,eventId:`fall-block-${headerRow}`,playedOn:""}));setBundle(next);
  }catch(cause){if(version===generation.current)setError(cause instanceof Error?cause.message:"The game snapshot could not be read.");}finally{if(version===generation.current)setBusy(false);}
 }
 const review=useMemo(()=>{if(!bundle)return null;try{return parseGameSource(bundle.snapshot,GAME_SOURCES[bundle.snapshot.source],identities.filter(m=>m.athleteCode),events.filter(event=>event.playedOn));}catch{return null;}},[bundle,identities,events]);
 const prepared=useMemo(()=>{if(!review?.canImport)return null;try{return validateGameImport({...review});}catch{return null;}},[review]);
 const nameByCode=new Map(athletes.map(a=>[a.code,a.name]));
 return <section className="panel p-5 sm:p-6"><fieldset disabled={pending||busy} className="m-0 min-w-0 border-0 p-0"><h2 className="text-xl font-bold">Review a Game Sheet Snapshot</h2><p className="muted text-sm">The daily check prepares this file from the approved tabs. Review player matches and actual pitching dates once, then retain those mappings for later runs. Only the reviewed numeric observations are sent to the shared dashboard.</p><label>Prepared snapshot<input type="file" onChange={event=>void read(event.target.files?.[0])}/></label>{busy&&<p role="status">Reading source snapshot…</p>}{error&&<p role="alert" className="notice notice-error">{error}</p>}
 {bundle&&<><p className="mt-4 font-semibold">{GAME_SOURCE_LABELS[bundle.snapshot.source]}</p><p className="muted text-xs">Source checked {new Date(bundle.snapshot.fetchedAt).toLocaleString()} · Blank source entries remain missing.</p><details className="mt-4 rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Review Player Matches</summary><p className="muted mt-2 text-xs">Exact full-name suggestions need review. Unknown identities are never assigned by partial names, jersey numbers or row position.</p><div className="grid gap-3 sm:grid-cols-2">{identities.map((mapping,index)=><label key={mapping.sourceName}>{mapping.sourceName}<select value={mapping.athleteCode} onChange={event=>{setApproved(false);setMappingApproved(false);setIdentities(current=>current.map((m,i)=>i===index?{...m,athleteCode:event.target.value}:m));}}><option value="">Unmapped</option>{athletes.map(a=><option key={a.code} value={a.code}>{a.name} · {a.code}</option>)}</select></label>)}</div></details>
 {bundle.snapshot.source==="pitching_fall_2026"&&<details className="mt-4 rounded-lg border p-4" open><summary className="cursor-pointer font-semibold">Review Pitching Game Dates</summary><p className="muted mt-2 text-xs">Enter the actual game date for each populated block. Empty blocks can remain undated.</p><div className="grid gap-3 sm:grid-cols-2">{events.map((event,index)=><label key={event.headerRow}>Source Rows {event.firstRow}–{event.lastRow}<input type="date" min="2026-09-01" max="2026-12-31" value={event.playedOn} onChange={change=>{setApproved(false);setMappingApproved(false);setEvents(current=>current.map((e,i)=>i===index?{...e,playedOn:change.target.value}:e));}}/></label>)}</div></details>}
 {review&&<><p role="status" className="mt-5 font-semibold">{review.observations.length} recorded values · {review.populatedRows} populated source rows</p>{review.issues.length>0&&<div role="alert" className="notice notice-error"><ul>{review.issues.slice(0,25).map((issue,index)=><li key={index}>{issue.row?`Row ${issue.row}: `:""}{issue.message}</li>)}</ul></div>}{!review.populatedRows&&<p className="muted">No entered statistics yet. Prepared formulas and empty cells will not become zero performances.</p>}{review.observations.length>0&&<div className="table-wrap mt-4"><table aria-label="Game Snapshot Review"><thead><tr><th>Player</th><th>Metric</th><th>Value</th><th>Period</th><th>Source</th></tr></thead><tbody>{review.observations.slice(0,limit).map((row,index)=><tr key={index}><td>{nameByCode.get(row.athleteCode)??"Unrecognized player"}</td><td>{row.label}</td><td>{row.value}{row.unit==="%"?"%":""}</td><td>{row.playedOn??"Fall cumulative"}</td><td>Row {row.sourceRow}, column {row.sourceColumn}</td></tr>)}</tbody></table></div>}{review.observations.length>limit&&<button type="button" className="btn btn-secondary mt-3" onClick={()=>setLimit(limit+100)}>Show More</button>}
 {prepared&&review.observations.every(row=>nameByCode.has(row.athleteCode))&&<div className="mt-5 space-y-4"><input type="hidden" name="snapshot" value={JSON.stringify(prepared)}/><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 !w-auto" name="confirm" value="yes" required checked={approved} onChange={event=>setApproved(event.target.checked)}/><span>I reviewed the full source snapshot, player matches, dates and recorded values and approve updating this Fall source.</span></label><SubmitButton disabled={!approved} pendingText="Syncing Game Stats…">Sync Game Stats</SubmitButton></div>}
 </>}
 <label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 !w-auto" checked={mappingApproved} onChange={event=>setMappingApproved(event.target.checked)}/><span>I verified the selected player matches and any listed game dates for future daily checks. Unmapped players will require review.</span></label><button type="button" disabled={!mappingApproved} className="btn btn-secondary mt-3" onClick={()=>{const blob=new Blob([JSON.stringify({version:1,source:bundle.snapshot.source,spreadsheetId:bundle.snapshot.spreadsheetId,sheetId:bundle.snapshot.sheetId,sheetTitle:bundle.snapshot.sheetTitle,reviewed:true,reviewedAt:new Date().toISOString(),identities:identities.filter(m=>m.athleteCode),events:events.filter(e=>e.playedOn)},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`pacu-${bundle.snapshot.source}-reviewed-mappings.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Save Reviewed Mappings for Daily Checks</button>
 </>}
 </fieldset></section>;
}
export function GameSnapshotImport({athletes,action}:{athletes:Choice[];action:(form:FormData)=>Promise<void>}){return <form action={action}><Fields athletes={athletes}/></form>;}
