"use client";
import { useState } from "react";
import { parseMovementPayload, type MovementPayload } from "@/lib/movement-screening";
import { MovementScreening } from "@/components/movement-screening";
import { saveMovementScreenings } from "@/app/(workspace)/imports/movement/actions";
export function MovementImport({roster}:{roster:{code:string;name:string}[]}){
 const [payload,setPayload]=useState<MovementPayload|null>(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[saved,setSaved]=useState(false);
 return <div className="space-y-5"><label className="block rounded-xl border border-dashed border-[var(--line-subtle)] p-5"><span className="mb-3 block font-semibold">Reviewed Movement Screening File</span><input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{setPayload(null);setReviewed(false);setSaved(false);setMessage("");const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error();const p=parseMovementPayload(JSON.parse(await file.text()));if(p.reports.some(r=>!roster.some(a=>a.code===r.athleteCode)))throw new Error();setPayload(p);}catch{setMessage("Choose a valid reviewed screening file with existing player matches.");}}}/></label>
 {payload&&<><p className="font-semibold">{payload.reports.length} matched players · Review all results below</p>{payload.reports.map(r=><details key={`${r.sheetId}:${r.screenedOn}`} className="rounded-xl border border-[var(--line-subtle)] p-4"><summary className="cursor-pointer font-bold">{roster.find(a=>a.code===r.athleteCode)?.name} <span className="muted ml-2 text-xs font-normal">{r.athleteCode} · {r.screenedOn}</span></summary><div className="pt-5"><MovementScreening report={r} showReferences/></div></details>)}<label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={reviewed} disabled={busy||saved} onChange={e=>setReviewed(e.target.checked)}/>I reviewed every player match, date, rating, source flag and range-of-motion result.</label><button className="btn btn-primary" disabled={!reviewed||busy||saved} onClick={async()=>{setBusy(true);setMessage("");try{const result=await saveMovementScreenings(payload,reviewed);if("error" in result)setMessage(result.error??"Save could not be verified.");else{setSaved(true);setMessage(`Verified saved results: ${result.created} new, ${result.unchanged} already saved · ${result.verified} profiles.`);}}catch{setMessage("Save status is uncertain. Check profiles before retrying this identical file.");}finally{setBusy(false);}}}>{busy?"Saving…":saved?"Saved & Verified":"Save Movement Screenings"}</button></>}
 {message&&<p role="status" className={`rounded-lg border p-4 text-sm ${saved?"border-emerald-500/40":"border-amber-500/40"}`}>{message}</p>}</div>;
}
