import Link from "next/link";
import { StatInfo } from "@/components/stat-info";
import { percentileColor } from "@/lib/percentile-color";
import styles from "./percentile-bar.module.css";
import ranks from "./leaderboard.module.css";
import { PHYSICALITY_METHOD, type PhysicalityComposite, type PhysicalityScore } from "@/lib/physicality-composite";
import { leaderboardSourceLabel, leaderboardTestDate } from "@/lib/leaderboards";

function ScoreMeter({ value }: { value: number }) {
  const color = percentileColor(value);
  return <div className={styles.meter} role="meter" aria-label="Physicality Score" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} aria-valuetext={`${value.toFixed(1)} out of 100; average of three component percentiles`}><div className={styles.track} aria-hidden="true"><span className={styles.fill} style={{ width: `${value}%`, backgroundColor: color.backgroundColor }} /><span className={styles.midpoint} /><span className={styles.marker} style={{left:`${value}%`,...color}}>{Math.round(value)}</span></div></div>;
}
function Method() { return <details className="mt-4 text-xs leading-6 text-[var(--text-secondary)]"><summary className="cursor-pointer font-semibold">How the Score Works</summary><p>{PHYSICALITY_METHOD}</p><p>Weight is excluded to avoid counting body size twice. Grip strength and speed tests remain separate. Source and units never mix; the comparison with the most complete players is used, with source and unit names breaking ties.</p></details>; }
export function PhysicalityScoreCard({ score, sampleSize, source }: { score?: PhysicalityScore; sampleSize: number; source: string }) {
  return <section className="panel p-5 sm:p-6" data-testid="physicality-score"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="m-0 text-lg font-bold">Physicality Score<StatInfo metric="physicality_score" label="Physicality Score" /></h2><span className="text-xs text-[var(--text-secondary)]">Fall 2026 · Version 1</span></div>
    {score ? <><div className="my-4 flex items-baseline gap-2"><strong className="text-4xl font-black tabular-nums">{score.value.toFixed(1)}</strong><span className="text-sm text-[var(--text-secondary)]">/ 100 · Rank {score.rank} of {sampleSize}</span></div><ScoreMeter value={score.value} /><p className="mt-3 text-xs text-[var(--text-secondary)]">{leaderboardSourceLabel(source)} · Last Tested {leaderboardTestDate(score.measuredAt)}</p><div className="grid grid-cols-3 gap-3 border-t border-[var(--line-subtle)] pt-4 text-xs">{([['height', 'Height'], ['muscle_mass', 'Muscle Mass'], ['body_fat_pct', 'Body Fat %']] as const).map(([key,label]) => <div key={key}><span className="block text-[var(--text-secondary)]">{label}</span><strong className="mt-1 block tabular-nums">{score.components[key].toFixed(1)} <span className="font-normal">percentile</span></strong></div>)}</div></> : <p className="mb-0 text-sm text-[var(--text-secondary)]">Awaiting comparable measurements. A score requires height, muscle mass and body fat % from the same test date, plus at least five complete players in the comparison.</p>}<Method /></section>;
}
export function PhysicalityCompositeBoard({ composite }: { composite: PhysicalityComposite }) {
  const table = (rows: PhysicalityScore[]) => <div className={ranks.tableWrap}><table><caption className="sr-only">Physicality composite score rankings, out of 100</caption><thead><tr><th>Rank</th><th>Player</th><th>Score</th></tr></thead><tbody>{rows.map(r => <tr key={r.athleteCode}><td><span className={`${ranks.rank} ${r.rank === 1 ? ranks.first : ""}`}>{r.rank}</span></td><th scope="row"><span className={ranks.player}>{r.profileId ? <Link href={`/athletes/${r.profileId}`} prefetch={false} className="text-link">{r.name}</Link> : r.name}</span><span className={ranks.playerMeta}>Last Tested {leaderboardTestDate(r.measuredAt)}</span></th><td className={ranks.result}>{r.value.toFixed(1)}<span className="ml-1 text-xs font-normal text-[var(--text-secondary)]">/100</span></td></tr>)}</tbody></table></div>;
  return <section className={`panel mb-6 ${ranks.card}`} data-testid="physicality-composite-board"><header className="p-5 sm:p-6"><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-[var(--accent-readable)]">Team Comparison · Fall 2026</div><h2 className="m-0 text-xl font-bold">Physicality Score<StatInfo metric="physicality_score" label="Physicality Score" /></h2><p className="mb-0 mt-2 text-xs text-[var(--text-secondary)]">Height · Total Muscle Mass · Body Fat %{composite.rows.length > 0 && ` · ${composite.sampleSize} Players · ${leaderboardSourceLabel(composite.source)}`}</p></header>{composite.rows.length ? <>{table(composite.rows.slice(0,5))}{composite.rows.length > 5 && <details className="border-t border-[var(--line-subtle)]"><summary className="cursor-pointer px-6 py-3 text-xs font-semibold">Show {composite.rows.length-5} More</summary>{table(composite.rows.slice(5))}</details>}</> : <p className="px-6 text-sm text-[var(--text-secondary)]">Awaiting five players with all three comparable measurements.</p>}<div className="border-t border-[var(--line-subtle)] px-5 pb-4 sm:px-6"><Method />{composite.excludedCount > 0 && <p className="text-xs text-[var(--text-secondary)]">{composite.excludedCount} measured players are missing a component or have different test dates. No partial scores are ranked.</p>}</div></section>;
}
