import {StatInfo} from "@/components/stat-info";
import {loggedBattingRates,loggedPitchingRates,type GameLog} from "@/lib/game-log";
import {LimitedSample} from "@/components/limited-sample";
const v=(n:number|undefined)=>n===undefined?"—":n;
export function PlayerGameLog({logs}:{logs:GameLog[]}){
 const ordered=[...logs].sort((a,b)=>b.playedOn.localeCompare(a.playedOn)||b.gameNumber-a.gameNumber||a.id.localeCompare(b.id));
 const batting=ordered.filter(l=>Object.keys(l.batting).length),pitching=ordered.filter(l=>Object.keys(l.pitching).length),recent=batting.slice(0,5),rates=loggedBattingRates(recent),recentPitching=pitching.slice(0,5),pitchRates=loggedPitchingRates(recentPitching);
 return <section className="panel mt-5 p-5 sm:p-6" aria-label="Dated game log"><h2 className="text-lg font-bold">Game Log</h2><p className="muted text-xs">Dated results entered by coaches · Separate from QPA sheet totals</p>{!logs.length?<p className="muted text-sm">Your first recorded game will appear here with its date and opponent.</p>:<>
 {rates.length>0&&<><h3 className="mt-5 text-sm font-bold">Recent Form · Last {recent.length} Logged Batting {recent.length===1?"Game":"Games"}</h3><p className="muted text-xs">{recent.at(-1)?.playedOn}–{recent[0].playedOn} · Combined opportunities, not an average of game percentages.</p><dl className="my-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{rates.map(r=><div key={r.label} className="rounded-xl border border-[var(--line-subtle)] p-3"><dt className="muted text-xs">{r.label}<StatInfo metric={{AVG:"batting_avg",OBP:"batting_obp",SLG:"game_log_slg",ISO:"game_log_iso","HR %":"batting_hr_pct","BB %":"batting_bb_pct","K %":"batting_k_pct"}[r.label]??r.label} label={r.label}/></dt><dd className="mt-2 text-2xl font-black tabular-nums">{r.unit==="%"?`${r.value.toFixed(1)}%`:r.value.toFixed(3).replace(/^0\./,".")}</dd><p className="muted mb-0 mt-1 text-xs">{r.opportunities} {r.opportunityLabel}</p><LimitedSample count={r.opportunities}/></div>)}</dl><p className="muted text-xs">Rates require their counts in every selected game. Missing counts stay unknown.</p></>}
 {batting.length>0&&<div className="table-wrap mt-5"><table aria-label="Dated batting games"><thead><tr><th>Date</th><th>Opponent</th><th>PA</th><th>AB</th><th>H</th><th>2B</th><th>3B</th><th>HR</th><th>BB</th><th>K</th></tr></thead><tbody>{batting.map(l=><tr key={l.id}><td className="whitespace-nowrap">{l.playedOn}</td><th scope="row">{l.opponent}<span className="muted block text-xs">{l.kind==="intrasquad"?"Intrasquad · ":""}Game {l.gameNumber}</span></th>{["pa","ab","h","doubles","triples","hr","bb","k"].map(k=><td key={k}>{v(l.batting[k])}</td>)}</tr>)}</tbody></table></div>}
 {pitchRates.length>0&&<><h3 className="mt-5 text-sm font-bold">Recent Form · Last {recentPitching.length} Logged Pitching {recentPitching.length===1?"Game":"Games"}</h3><dl className="my-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{pitchRates.map(r=><div key={r.label} className="rounded-xl border border-[var(--line-subtle)] p-3"><dt className="muted text-xs">{r.label}</dt><dd className="mt-2 text-2xl font-black tabular-nums">{r.value.toFixed(1)}%</dd><p className="muted mb-0 mt-1 text-xs">{r.opportunities} {r.opportunityLabel}</p><LimitedSample count={r.opportunities} pitching={r.opportunityLabel==="pitches"} opportunityLabel={r.opportunityLabel}/></div>)}</dl></>}
 {pitching.length>0&&<div className="table-wrap mt-5"><table aria-label="Dated pitching games"><thead><tr><th>Date</th><th>Opponent</th><th>Pitches</th><th>Strike %</th><th>BF</th><th>K</th><th>BB</th><th>Outs</th></tr></thead><tbody>{pitching.map(l=><tr key={l.id}><td className="whitespace-nowrap">{l.playedOn}</td><th scope="row">{l.opponent}<span className="muted block text-xs">Game {l.gameNumber}</span></th><td>{v(l.pitching.pitches)}</td><td>{l.pitching.strikes!==undefined&&l.pitching.pitches>0?`${(100*l.pitching.strikes/l.pitching.pitches).toFixed(1)}%`:"—"}<LimitedSample count={l.pitching.pitches} pitching/></td>{["bf","k","bb","outs"].map(k=><td key={k}>{v(l.pitching[k])}</td>)}</tr>)}</tbody></table></div>}
 <p className="muted mt-4 text-xs">Updated {new Date([...logs].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0].updatedAt).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric",year:"numeric"})} · Review-only sample labels do not exclude results.</p></>}</section>;
}
