import Link from "next/link";
import { ArrowUpRight, UsersRound } from "lucide-react";
import { athleteName, display, type AthleteSeason, type RosterAthlete } from "@/lib/types";
export type RosterTableAthlete = Pick<RosterAthlete, "id" | "athlete_code" | "first_name" | "preferred_name" | "last_name"> & { athlete_seasons: Pick<AthleteSeason, "season" | "jersey_number" | "primary_position" | "academic_class">[] };
export function RosterTable({ athletes, season, profileBasePath = "/athletes" }: { athletes: RosterTableAthlete[]; season?: string; profileBasePath?: string }) {
  if (!athletes.length) return <div className="panel p-12 text-center"><UsersRound className="mx-auto mb-4 text-gray-400" size={30} /><h2 className="text-lg font-semibold">No athletes to show</h2><p className="muted mb-0 text-sm">Try a different season or ask an administrator to import the roster.</p></div>;
  return <div className="panel table-wrap"><table className="team-roster-table"><caption className="sr-only">Athlete roster{season ? ` for ${season}` : ""}</caption><thead><tr><th>Athlete</th><th className="hidden sm:table-cell">Athlete ID</th><th className="hidden sm:table-cell">Jersey</th><th>Position</th><th className="hidden md:table-cell">Class</th><th><span className="sr-only">Profile</span></th></tr></thead><tbody>{athletes.map(a => {
    const s = season ? a.athlete_seasons.find(s => s.season === season) : [...a.athlete_seasons].sort((a,b) => b.season.localeCompare(a.season))[0];
    return <tr key={a.id}><td><Link className="flex items-center gap-3 text-inherit no-underline" href={`${profileBasePath}/${a.id}`}><span className="roster-initials flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--surface-raised)] text-xs font-bold text-[var(--text-secondary)]" aria-hidden="true">{(a.preferred_name || a.first_name)[0]}{a.last_name[0]}</span><span className="min-w-0"><span className="roster-player-name font-semibold">{athleteName(a)}</span><span className="mt-1 block font-mono text-[10px] text-[var(--text-secondary)] sm:hidden">{a.athlete_code}</span></span></Link></td><td className="hidden font-mono text-xs text-[var(--text-secondary)] sm:table-cell">{a.athlete_code}</td><td className="hidden font-semibold sm:table-cell">{display(s?.jersey_number)}</td><td><span className="block whitespace-nowrap">{display(s?.primary_position)}</span>{s?.jersey_number !== null && s?.jersey_number !== undefined && <span className="mt-1 block text-xs text-[var(--text-secondary)] sm:hidden">#{s.jersey_number}</span>}</td><td className="hidden capitalize md:table-cell">{display(s?.academic_class)}</td><td><Link href={`${profileBasePath}/${a.id}`} aria-label={`View ${athleteName(a)} profile`} className="roster-profile-link text-[var(--text-secondary)]"><ArrowUpRight size={18} aria-hidden="true" /></Link></td></tr>;
  })}</tbody></table></div>;
}
