"use client";
import { useState } from "react";
import Link from "next/link";
import { COACHING_CATEGORIES, coachingVariables, coachingValue, progressRows, type CoachingData, type CoachingCategory } from "@/lib/coaching-tools";
import { leaderboardTestDate } from "@/lib/leaderboards";
import { StatInfo } from "@/components/stat-info";
import styles from "./coaching-tools.module.css";
export function CoachingTabs({value,onChange,games=false}:{value:string;onChange:(value:string)=>void;games?:boolean}){
 return <div className={styles.tabs} aria-label="Measurement category">{[...COACHING_CATEGORIES,...(games?["Game Stats"]:[])].map(category=><button key={category} type="button" aria-pressed={value===category} onClick={()=>onChange(category)}>{category}</button>)}</div>;
}
export function TeamProgress({data,today}:{data:CoachingData;today:string}){
 const [category,setCategory]=useState<CoachingCategory>("Physicality"),[selected,setSelected]=useState(""),[interval,setInterval]=useState(30);
 const variables=coachingVariables(data,category,today),variable=variables.find(v=>v.key===selected)??variables[0];
 const rows=variable?progressRows(data,variable.key,today,interval):[];
 const comparable=rows.filter(r=>r.delta!==null),increased=comparable.filter(r=>r.delta!>0),decreased=comparable.filter(r=>r.delta!<0),due=rows.filter(r=>r.due);
 const scale=Math.max(1,...comparable.map(r=>Math.abs(r.percent??0)));
 return <div className={styles.tools}><CoachingTabs value={category} onChange={value=>{setCategory(value as CoachingCategory);setSelected("");}}/>
  <div className={styles.toolbar}><label className={`${styles.field} ${styles.metricField}`}>Choose a Test<select aria-label="Progress measurement" value={variable?.key??""} onChange={e=>setSelected(e.target.value)} disabled={!variables.length}>{!variables.length&&<option value="">No recorded {category.toLowerCase()} tests</option>}{variables.map(v=><option key={v.key} value={v.key}>{v.label} · {v.source} · {v.unit}</option>)}</select></label><label className={styles.field}>Retest After<select value={interval} onChange={e=>setInterval(Number(e.target.value))}>{[7,14,30,60].map(n=><option value={n} key={n}>{n} days</option>)}</select></label><span className={styles.meta}>As of {leaderboardTestDate(today)} · Fall 2026</span></div>
  {variable?<><div className={styles.summary} aria-label="Testing summary"><div><strong>{comparable.length}</strong><span>Repeat tests to compare</span></div><div><strong>{increased.length}</strong><span>Increased</span></div><div><strong>{decreased.length}</strong><span>Decreased</span></div><div><strong>{due.length}</strong><span>Need testing or retesting</span></div></div>
  <section className={styles.panel} aria-label="Changes since previous testing"><div className={styles.panelHead}><div><h2>{variable.label}<StatInfo metric={variable.metric} label={variable.label}/></h2><p className={styles.meta}>Latest Fall test vs. previous test · {variable.source} · {variable.unit}</p></div><span className={styles.meta}>Biggest changes first</span></div>
  {!comparable.length&&<div className={styles.notice}>Repeat testing will fill this chart. First results are grouped below; they do not count as a gain or decline.</div>}
  {rows.filter(r=>r.delta!==null||r.conflict).map(row=><div className={styles.row} key={row.player.id}><div><Link prefetch={false} className={styles.name} href={`/athletes/${row.player.id}`}>{row.player.name}</Link><p className={styles.meta}>{row.player.position||"Position pending"}{row.due?" · Retest due":""}</p></div><div><span className="text-xs font-semibold tabular-nums">{row.previous?`${coachingValue(row.previous.value,variable.metric,variable.unit,variable.source)} → `:""}{row.latest?coachingValue(row.latest.value,variable.metric,variable.unit,variable.source):"Needs review"}</span><p className={styles.meta}>{row.previous&&`${leaderboardTestDate(row.previous.date)} → `}{row.latest&&leaderboardTestDate(row.latest.date)}{row.conflict&&" · Conflicting same-day results"}</p></div><div className={`${styles.diverging} ${styles[row.tone]}`} aria-hidden="true">{row.percent!==null&&<span style={{left:row.percent<0?`${50-Math.abs(row.percent)/scale*50}%`:"50%",width:`${Math.abs(row.percent)/scale*50}%`}}/>}</div><div className={`${styles.delta} ${styles[row.tone]}`}>{row.percent!==null?`${row.percent>0?"+":""}${row.percent.toFixed(1)}%`:row.delta!==null?"—":row.conflict?"Review":"First Test"}{row.previous?.value===0&&<p className={styles.meta}>Previous value 0</p>}</div></div>)}
  {!rows.some(r=>r.delta!==null||r.conflict)&&<p className={styles.empty}>No repeat changes to plot yet.</p>}</section>
  {rows.some(r=>r.latest&&!r.previous&&!r.conflict)&&<details className={`${styles.panel} ${styles.details}`}><summary>First Test Results · {rows.filter(r=>r.latest&&!r.previous&&!r.conflict).length}</summary><ul className={styles.dueList}>{rows.filter(r=>r.latest&&!r.previous&&!r.conflict).map(row=><li key={row.player.id}><Link prefetch={false} className={styles.name} href={`/athletes/${row.player.id}`}>{row.player.name}</Link><p className={styles.meta}>{coachingValue(row.latest!.value,variable.metric,variable.unit,variable.source)} · {leaderboardTestDate(row.latest!.date)}{row.due?" · Retest due":""}</p></li>)}</ul></details>}
  <details className={`${styles.panel} ${styles.details}`}><summary>Testing Queue · {due.length} {due.length===1?"player":"players"}</summary><p className={styles.meta}>No Fall result, or more than {interval} days since the latest result for this source. <Link prefetch={false} href="/testing">Open Testing</Link></p><ul className={styles.dueList}>{due.map(row=><li key={row.player.id}><Link prefetch={false} className={styles.name} href={`/athletes/${row.player.id}`}>{row.player.name}</Link><p className={styles.meta}>{row.latest?`Last tested ${leaderboardTestDate(row.latest.date)}`:"Needs first Fall test"}</p></li>)}</ul>{!due.length&&<p className={styles.meta}>Everyone eligible is current for this measurement.</p>}</details>
  <details className={`${styles.panel} ${styles.details}`}><summary>How to Read This View</summary><p className={styles.meta}>The bars show change since the previous test, not a team ranking. Left means the number went down; right means it went up. Green marks gains in muscle mass or body score, lower body fat, and better performance times. Red marks the opposite. Height, weight, and spin stay neutral. We compare the same test and units each time. If two results from the same day disagree, a coach should review them.</p><p className={styles.meta}>{rows.length} eligible players · {comparable.filter(r=>r.delta===0).length} unchanged · {rows.filter(r=>r.conflict).length} needing review</p></details></>:<section className={`${styles.panel} ${styles.empty}`}><h2 className="text-base">Ready for {category} Testing</h2><p>Charts will appear when results are saved. Coaches can add measurements in <Link prefetch={false} href="/imports">Import Center</Link> or <Link prefetch={false} href="/testing">Testing</Link>.</p></section>}
 </div>;
}
