import { RENPHO_SEGMENTS } from "@/lib/renpho-segments";
import { PLAYER_METRICS, normalizePlayerMetric } from "@/lib/player-performance";

// Short descriptions of recorded measures, not targets or medical interpretations.
export const STAT_DEFINITIONS: Readonly<Record<string, string>> = {
  ...Object.fromEntries(RENPHO_SEGMENTS.map(segment => [segment.label.toLowerCase(), "Estimated muscle mass for this body part from RENPHO’s Muscle Balance section. The mass is separate from the percentage compared with the device’s standard and is not a strength measurement."])),
  body_score: "The Body Score printed in the top-right corner of the RENPHO report, on its /100 scale. This is the device’s recorded score; PACU does not calculate or combine measurements to produce it. Some reports may exceed 100. It is not a team percentile.",
  height: "Recorded standing height. Displayed in feet and inches; comparisons keep the original measurement units separate.",
  weight: "Total recorded body weight on the test date. A higher percentile means a higher measured weight, not a better score.",
  grip_strength: "Force measured during a grip-strength test. Compare results taken with the same device, hand, and testing protocol.",
  body_fat_pct: "The report’s estimated fat mass as a percentage of body weight. This is a body-composition measurement, not a performance rating.",
  skeletal_muscle_mass: "The device’s estimated skeletal muscle mass, in pounds or kilograms. This is separate from total muscle mass and is not a strength test.",
  muscle_mass: "Total muscle mass reported by the device, in pounds or kilograms. It is separate from skeletal muscle mass and muscle mass percentage.",
  muscle_mass_pct: "Reported muscle mass as a percentage of body weight. Calculated readings use muscle mass and weight from the same report.",
  max_exit_velocity: "The highest recorded speed of a batted ball leaving the bat in the reviewed session.",
  avg_exit_velocity: "The average recorded batted-ball exit speed for the swings included in the source session summary.",
  bat_speed: "Recorded bat speed. This legacy field does not specify whether the value is a maximum or an average; those measures have separate cards.",
  max_bat_speed: "The highest recorded bat speed in the reviewed session. Blast measures speed at the bat’s sweet spot at impact. Device sources are compared separately.",
  avg_bat_speed: "The average bat speed for the swings included in the reviewed session summary. The source determines which swings are included.",
  smash_factor: "Exit velocity divided by bat speed, with both speeds in the same units. The dashboard imports the source’s reviewed ratio; it does not divide unrelated session averages.",
  max_distance: "The greatest recorded batted-ball distance in the reviewed session. Measured and projected distances depend on the source device.",
  home_to_first: "Elapsed time from home to first base using the team’s testing protocol. A shorter time receives a higher performance percentile.",
  home_to_second: "Elapsed time from home to second base using the team’s testing protocol. Keep start and stop rules consistent between tests.",
  steal_break: "Elapsed time for the team’s steal-break test. The coach’s start and finish points determine the test; compare the same protocol.",
  boxer_t: "Completion time for the team’s Boxer T agility test. Compare tests using the same course and timing rules.",
  max_pitch_velocity: "The highest recorded pitch speed in the reviewed session.",
  avg_pitch_velocity: "Average pitch speed for the pitches included in the reviewed session summary. It is not automatically a fastball-only average.",
  avg_fastball_spin: "Average fastball rotation rate, in revolutions per minute. Only fastballs belong in this metric; a higher spin value is not automatically a better pitch.",
  strike_pct: "Strikes divided by total pitches, multiplied by 100. This measures pitch-level strike frequency, not strikeouts.",
  k_pct: "Strikeouts divided by batters faced, multiplied by 100. This is different from Strike %.",
  bb_pct: "Walks divided by batters faced, multiplied by 100. Use the same walk-counting rules as the source.",
  infield_velocity: "Recorded throwing speed during the team’s infield throwing test. Compare throws taken under the same testing conditions.",
  outfield_velocity: "Recorded throwing speed during the team’s outfield throwing test. Compare throws taken under the same testing conditions.",
  "body fat mass": "Estimated total fat mass in the report’s recorded weight unit.",
  "bone mass": "The device’s estimated bone mass. This is not a bone-density measurement.",
  "protein mass": "The device’s estimated mass of protein in the body, in the recorded weight unit.",
  "body water mass": "The device’s estimated total body water, expressed as mass.",
  "skeletal muscle mass": "The device’s estimated skeletal muscle mass. This is a different field from total Muscle Mass.",
  "fat-free mass": "The report’s estimated body mass excluding fat. It includes muscle, water, bone, and other non-fat tissue.",
  "subcutaneous fat": "The device’s estimated percentage of fat beneath the skin.",
  "body water percentage": "The device’s estimated body water as a percentage of total body weight.",
  "protein percentage": "The device’s estimated protein mass as a percentage of body weight.",
  "bone mass percentage": "The device’s estimated bone mass as a percentage of body weight.",
  "skeletal muscle percentage": "The device’s estimated skeletal muscle mass as a percentage of body weight.",
  bmi: "Body mass index: weight in kilograms divided by height in meters squared. It does not distinguish muscle from fat.",
  bmr: "The device’s estimate of energy used at rest. This is a recorded estimate, not a calorie-intake recommendation.",
  "visceral fat": "The device’s visceral-fat rating. The report uses an index or grade, not pounds or a body-fat percentage.",
  "metabolic age": "A device-generated comparison of estimated metabolism with its age reference data. It is not the player’s actual age.",
  "skeletal muscle index": "The skeletal muscle index reported by the device, in kg/m². Retained as reported without inferring its calculation method.",
  "waist-to-hip ratio": "Waist circumference divided by hip circumference, as reported by the device.",
  batting_hr_pct: "Home run rate: Pumps (home runs) divided by plate appearances × 100. For example, 2 HR in 40 PA is 5%. Measures home-run frequency; it does not include doubles or triples and is not ISO or slugging percentage.",
  batting_obp: "On-base percentage: (all hits + walks + hit-by-pitches) / (at-bats + walks + hit-by-pitches + sacrifice flies). Sacrifice bunts are excluded.",
  batting_hh_pct: "QPA sheet hard-hit percentage: (HH Base Hit + 3–8 HH + HH Extra Base Hit + Pumps) / (AB − Punchies − Sac Bunt). Uses the team's sheet formula, not Statcast's exit-velocity threshold.",
  sac_fly: "Recorded sacrifice flies; included in the OBP denominator, excluded from at-bats.",
  batting_avg: "Batting average: all hits divided by official at-bats. The team confirmed Base Hit contains every hit; overlapping hard-hit columns are not added again. Displayed to three decimals.",
  batting_bb_pct: "Batting walk rate: walks divided by plate appearances, multiplied by 100. This is not the pitching walk-rate metric.",
  batting_k_pct: "Batting strikeout rate: recorded Punchies divided by plate appearances, multiplied by 100.",
  base_hit: "All hits recorded in the QPA sheet, as confirmed by the team. Hard-hit columns overlap this total and are not added to it.",
  pumps: "Home runs, recorded as Pumps in the QPA sheet.",
  sb: "Stolen bases recorded in the QPA sheet.",
  gdp: "Grounded into double plays recorded in the QPA sheet.",
  hh_base_hit: "The QPA sheet’s hard-hit base-hit category. It overlaps the total Base Hit field; do not add it again to calculate total hits.",
  hh_extra_base_hit: "The QPA sheet’s hard-hit extra-base-hit category. It is not a doubles/triples breakdown and cannot determine ISO.",
  pa: "Plate appearances recorded in the team’s game sheet.", ab: "Official at-bats recorded in the team’s game sheet.",
  qpa: "Quality plate appearances credited under the team’s QPA scoring rules.",
  qpa_pct: "Quality plate appearances divided by plate appearances, multiplied by 100, using the team sheet’s recorded totals.",
  pitches: "Total pitches recorded for this outing.", strikes: "Pitches recorded as strikes in the team sheet.",
  k: "Strikeouts recorded in the team sheet.", bb: "Walks recorded in the team sheet.", bb_outcome: "Walks allowed. This is separate from the sheet’s BB breaking-ball pitch family.",
  h: "Hits recorded in the team sheet.", r: "Runs recorded in the team sheet.", rbi: "Runs batted in recorded in the team sheet.",
  hbp: "Hit-by-pitch outcomes recorded in the team sheet.",
  fb: "Fastball pitches recorded in the pitching sheet.", fb_k: "The pitching sheet’s fastball strike count; K here denotes strikes, not strikeouts.",
  ch: "Changeup pitches recorded in the pitching sheet.", ch_k: "The pitching sheet’s changeup strike count; K here denotes strikes, not strikeouts.",
  bb_pitch_family: "Breaking-ball pitches recorded in the pitching sheet. This BB field does not mean walks.",
  bb_pitch_family_k: "The pitching sheet’s breaking-ball strike count. This is separate from walks and strikeouts.",
};

export function statDefinition(metric: string): string {
  if(metric.startsWith("qpa_game_"))return statDefinition(metric.slice(9));
  const definition = PLAYER_METRICS.find(item => item.key === metric || item.label.toLowerCase() === metric.toLowerCase())
    ?? PLAYER_METRICS.find(item => item.units.some(unit => normalizePlayerMetric(metric, unit)?.key === item.key));
  return STAT_DEFINITIONS[definition?.key ?? metric.toLowerCase()] ?? "This is a recorded field from the source report or team sheet. Its scoring rules follow that source; a team-specific definition has not been confirmed yet.";
}
