import { BLAST_ALL_METRICS } from "@/lib/blast-metrics";
import { RENPHO_SEGMENTS } from "@/lib/renpho-segments";
import { PLAYER_METRICS, normalizePlayerMetric } from "@/lib/player-performance";

// Short descriptions of recorded measures, not targets or medical interpretations.
export const STAT_DEFINITIONS: Readonly<Record<string, string>> = {
  pearson_r: "How closely do these two stats move together for the players shown? Pearson r runs from −1 to +1. Positive means they tend to rise together; negative means one tends to fall as the other rises. Near 0 means little straight-line pattern. It takes at least five players to show a score, and a strong score does not mean one stat causes the other.",
  r_squared: "How much of the spread in the second stat follows the trend line? R² runs from 0 to 1. A score of 0.64 means the line accounts for 64% of that stat’s variation among the players shown. It is not a prediction score or proof that one stat causes the other.",
  hitter_contact_map: "See where recorded batted balls sit by exit speed, launch angle, and field direction. Choose a game, intrasquad, or practice session above. Only balls with the needed Full Swing readings appear; the chart does not tell us whether they were hits.",
  ev_launch_chart: "Each dot is one batted ball. Farther right means it came off the bat faster; higher means it was hit at a higher angle. Color also shows exit speed. Hard hit means 90+ mph here, and the launch window is 8–32°. The percentages count balls with both readings in the selected session.",
  spray_chart: "Each dot shows a recorded ball’s direction and distance. Positive direction points toward first base. The 150-foot line separates infield from outfield on this chart; pull and opposite depend on the hitter’s batting side. These are ball-flight readings, not confirmed hits or exact landing spots.",
  pitch_arsenal_chart: "Each mark is a pitch type assigned by the staff in this session. Farther right means a higher average velocity; higher means more average spin. The velocity and spin averages can come from different numbers of recorded pitches. This compares readings, not how effective a pitch is.",
  pitch_mix_chart: "Each slice shows how often a staff-assigned pitch type was thrown in this session. Pitches without an assignment, or pitches left out of the dashboard, are not part of the total. The slices may not represent every pitch thrown.",
  pitching_contact_chart: "This bar shows the split between weak and hard contact recorded by coaches in the Fall pitching sheet. Each share is out of weak plus hard contact when both counts are available. These labels come from the team sheet; they do not use the hitter chart’s 90 mph hard-hit rule.",
  ...Object.fromEntries(BLAST_ALL_METRICS.map(m=>[m.key,m.description])),
  blast_peak_hand_speed: "Hand speed uses Blast’s per-swing Peak Hand Speed metric. The Fall average weights each non-overlapping weekly average by its reported swing count. Latest Week Peak shows the vendor’s weekly 95th percentile, not a Fall maximum.",
  p95_bat_speed: "Blast’s 95th-percentile bat speed for the selected week: a strong-swing mark, not the single fastest swing. The separate Pacific percentile bar compares that weekly mark with teammates from the same reporting period.",
  classified_avg_velocity: "Average velocity of recorded pitches assigned to this pitch type by staff, within the player’s latest comparable session. In-game and Practice results remain separate; missing readings are excluded.",
  classified_max_velocity: "Highest recorded velocity for this staff-reviewed pitch type. The leaderboard uses the Fall best; profile session details show each saved session. In-game and Practice stay separate.",
  classified_avg_spin: "Average recorded spin rate (RPM) for this staff-reviewed pitch type in the latest comparable session. Higher spin ranks first numerically; more spin is not universally better, especially for changeups.",
  classified_max_spin: "Highest recorded spin rate (RPM) for this staff-reviewed pitch type. The leaderboard uses the Fall best; profile session details show each saved session. This is a numerical ranking, not a pitch-quality score.",
  ...Object.fromEntries(RENPHO_SEGMENTS.map(segment => [segment.label.toLowerCase(), "Estimated muscle mass for this body part from RENPHO’s Muscle Balance section. The mass is separate from the percentage compared with the device’s standard and is not a strength measurement."])),
  body_score: "The Body Score printed in the top-right corner of the RENPHO report, on its /100 scale. This is the device’s recorded score; PACU does not calculate or combine measurements to produce it. Some reports may exceed 100. It is not a team percentile.",
  height: "Recorded standing height. Displayed in feet and inches; comparisons keep the original measurement units separate.",
  weight: "Total recorded body weight on the test date. A higher percentile means a higher measured weight, not a better score.",
  grip_dominant: "Grip force recorded for the dominant hand. Compare the same hand, device, protocol and unit; this is separate from non-dominant grip.",
  grip_non_dominant: "Grip force recorded for the non-dominant hand. Compare the same hand, device, protocol and unit; this is separate from dominant grip.",
  grip_strength: "Force measured during a grip-strength test. Compare results taken with the same device, hand, and testing protocol.",
  body_fat_pct: "The report’s estimated fat mass as a percentage of body weight. Lower body fat receives a higher percentile and leaderboard rank. This is a body-composition comparison, not a performance rating.",
  skeletal_muscle_mass: "The device’s estimated skeletal muscle mass, in pounds or kilograms. This is separate from total muscle mass and is not a strength test.",
  muscle_mass: "Total muscle mass reported by the device, in pounds or kilograms. It is separate from skeletal muscle mass and muscle mass percentage.",
  muscle_mass_pct: "Reported muscle mass as a percentage of body weight. Calculated readings use muscle mass and weight from the same report.",
  max_exit_velocity: "Highest recorded exit velocity. The leaderboard uses the Fall best in this source; the profile card shows the latest session. In-game and Practice stay separate.",
  avg_exit_velocity: "The average recorded batted-ball exit speed for the swings included in the source session summary.",
  bat_speed: "Recorded bat speed. This legacy field does not specify whether the value is a maximum or an average; those measures have separate cards.",
  max_bat_speed: "Highest recorded bat speed. The leaderboard uses the Fall best in this source; the profile card shows the latest session. Device sources stay separate.",
  avg_bat_speed: "The average bat speed for the swings included in the reviewed session summary. The source determines which swings are included.",
  smash_factor: "Exit velocity divided by bat speed, with both speeds in the same units. The dashboard imports the source’s reviewed ratio; it does not divide unrelated session averages.",
  max_distance: "Greatest recorded batted-ball distance. The leaderboard uses the Fall best in this source; the profile card shows the latest session. Measured and projected distances depend on the device.",
  steal_start_12ft: "The Player Metrics sheet’s 12 ft steal-start protocol. Best is the fastest recorded Fall trial; average uses all recorded trials from this protocol. Blank trials are excluded. This is separate from reaction and 12–42 ft split timing.",
  steal_reaction: "The Player Metrics sheet’s steal-start reaction timing. Keep this separate from the 12 ft start and the 12–42 ft split. Best is fastest; average includes recorded Fall trials only.",
  steal_12_42ft: "Elapsed time for the Player Metrics sheet’s 12–42 ft steal-start segment. Best is fastest; average includes recorded Fall trials only. Do not combine this split with reaction timing.",
  home_to_first: "Elapsed time from home to first base using the team’s testing protocol. A shorter time receives a higher performance percentile.",
  home_to_second: "Elapsed time from home to second base using the team’s testing protocol. Keep start and stop rules consistent between tests.",
  steal_break: "Elapsed time for the team’s steal-break test. The coach’s start and finish points determine the test; compare the same protocol.",
  boxer_t: "Completion time for the team’s Boxer T agility test. Compare tests using the same course and timing rules.",
  max_pitch_velocity: "Highest recorded pitch speed. The leaderboard uses the Fall best in this source; the profile card shows the latest session. In-game and Practice stay separate.",
  avg_pitch_velocity: "Average pitch speed for the pitches included in the reviewed session summary. It is not automatically a fastball-only average.",
  avg_fastball_spin: "Average fastball rotation rate, in revolutions per minute. Only fastballs belong in this metric; a higher spin value is not automatically a better pitch.",
  weak_contact_pct: "Of the balls the team marked weak or hard in this pitching period, the share marked weak. Higher ranks first. Balls without one of those labels are not counted.",
  hard_contact_pct: "Of the balls the team marked weak or hard in this pitching period, the share marked hard. Lower ranks first. This uses the team’s scoring labels, not a Statcast exit-speed cutoff.",
  weak_contact: "Weak-contact count recorded in the Pitching sheet’s Wk column for this period. This is a count, not a contact rate.",
  hard_contact: "Hard-contact count recorded in the Pitching sheet’s Hrd column for this period. The team’s scoring definition applies; this is not a Statcast exit-velocity threshold.",
  strike_pct: "Strikes divided by total pitches, multiplied by 100. This measures pitch-level strike frequency, not strikeouts.",
  k_pct: "Strikeouts divided by batters faced, multiplied by 100. This is different from Strike %.",
  bb_pct: "Walks divided by batters faced, multiplied by 100. Use the same walk-counting rules as the source.",
  infield_velocity: "Recorded throwing speed during the team’s infield throwing test. Compare throws taken under the same testing conditions.",
  outfield_velocity: "Recorded throwing speed during the team’s outfield throwing test. Compare throws taken under the same testing conditions.",
  "body fat mass": "Estimated total fat mass in the report’s recorded weight unit.",
  "bone mass": "The device’s estimated bone mass. This is not a bone-density measurement.",
  "protein mass": "The device’s estimated mass of protein in the body, in the recorded weight unit.",
  "body water mass": "The device’s estimated total body water, expressed as mass.",
  "skeletal muscle mass": "The device’s estimated skeletal muscle mass. This is a different field from total Muscle Mass.",
  "fat-free mass": "The report’s estimated body mass excluding fat. It includes muscle, water, bone, and other non-fat tissue.",
  "subcutaneous fat": "The device’s estimated percentage of fat beneath the skin.",
  "body water percentage": "The device’s estimated body water as a percentage of total body weight.",
  "protein percentage": "The device’s estimated protein mass as a percentage of body weight.",
  "bone mass percentage": "The device’s estimated bone mass as a percentage of body weight.",
  "skeletal muscle percentage": "The device’s estimated skeletal muscle mass as a percentage of body weight.",
  bmi: "Body mass index: weight in kilograms divided by height in meters squared. It does not distinguish muscle from fat.",
  bmr: "The device’s estimate of energy used at rest. This is a recorded estimate, not a calorie-intake recommendation.",
  "visceral fat": "The device’s visceral-fat rating. The report uses an index or grade, not pounds or a body-fat percentage.",
  "metabolic age": "A device-generated comparison of estimated metabolism with its age reference data. It is not the player’s actual age.",
  "skeletal muscle index": "The skeletal muscle index reported by the device, in kg/m². Retained as reported without inferring its calculation method.",
  "waist-to-hip ratio": "Waist circumference divided by hip circumference, as reported by the device.",
  game_log_slg: "Slugging percentage: (Hits + Doubles + 2 × Triples + 3 × Home Runs) / AB. Uses complete recorded hit types from dated game logs, separate from QPA totals.",
  game_log_iso: "Isolated power: (Doubles + 2 × Triples + 3 × Home Runs) / AB. Requires complete extra-base-hit counts in the selected dated games.",
  batting_hr_pct: "Home run rate: Pumps (home runs) divided by plate appearances × 100. For example, 2 HR in 40 PA is 5%. Measures home-run frequency; it does not include doubles or triples and is not ISO or slugging percentage.",
  batting_obp: "On-base percentage: (all hits + walks + hit-by-pitches) / (at-bats + walks + hit-by-pitches + sacrifice flies). Sacrifice bunts are excluded.",
  batting_hh_pct: "Share of eligible at-bats marked hard hit in the QPA sheet. The team counts HH Base Hit, 3–8 HH, HH Extra Base Hit, and Pumps; opportunities are AB minus strikeouts and sac bunts. This is the team’s scoring rule, not a Statcast exit-speed cutoff.",
  sac_fly: "Recorded sacrifice flies; included in the OBP denominator, excluded from at-bats.",
  batting_avg: "Batting average: all hits divided by official at-bats. The team confirmed Base Hit contains every hit; overlapping hard-hit columns are not added again. Displayed to three decimals.",
  batting_bb_pct: "Batting walk rate: walks divided by plate appearances, multiplied by 100. This is not the pitching walk-rate metric.",
  batting_k_pct: "Batting strikeout rate: recorded Punchies divided by plate appearances, multiplied by 100.",
  base_hit: "All hits recorded in the QPA sheet, as confirmed by the team. Hard-hit columns overlap this total and are not added to it.",
  pumps: "Home runs, recorded as Pumps in the QPA sheet.",
  batting_sb_per_pa: "Stolen bases divided by plate appearances. For example, 4 SB in 40 PA is 0.100 SB/PA. This describes stolen-base frequency, not success rate; caught-stealing counts are needed for success rate. More than one steal can occur after a plate appearance.",
  sb: "Stolen bases recorded in the QPA sheet.",
  gdp: "Grounded into double plays recorded in the QPA sheet.",
  hh_base_hit: "The QPA sheet’s hard-hit base-hit category. It overlaps the total Base Hit field; do not add it again to calculate total hits.",
  hh_extra_base_hit: "The QPA sheet’s hard-hit extra-base-hit category. It is not a doubles/triples breakdown and cannot determine ISO.",
  pa: "Plate appearances recorded in the team’s game sheet.", ab: "Official at-bats recorded in the team’s game sheet.",
  qpa: "Quality plate appearances credited under the team’s QPA scoring rules.",
  qpa_pct: "Quality plate appearances divided by plate appearances, multiplied by 100, using the team sheet’s recorded totals.",
  innings_outs: "Innings pitched stored as outs. For example, 1.1 IP is four outs, not 1.1 decimal innings. The team also enters .33/.67 for one/two outs.",
  earned_runs: "Earned runs recorded separately in the ER column. Total runs allowed are never substituted for earned runs.",
  pitching_k9: "How many strikeouts this pitcher would have over nine innings at the recorded pace. Calculated from strikeouts and outs pitched; .1 IP means one out and .2 IP means two outs. More ranks higher.",
  pitching_bb9: "How many walks this pitcher would allow over nine innings at the recorded pace. Calculated from walks allowed and outs pitched. Fewer ranks higher.",
  pitching_r9: "How many total runs this pitcher would allow over nine innings at the recorded pace. It includes earned and unearned runs, so it is not ERA. Fewer ranks higher.",
  pitch_splits: "Pitch usage is each recorded family’s pitch count divided by all pitches. Family strike percentage uses only that family’s strikes and pitches. The sheet groups breaking balls together; slider and curveball splits are unavailable.",
  pitches: "Total pitches recorded for this period.", strikes: "Pitches recorded as strikes in the team sheet.",
  k: "Strikeouts recorded in the team sheet.", bb: "Walks recorded in the team sheet.", bb_outcome: "Walks allowed. This is separate from the sheet’s BB breaking-ball pitch family.",
  h: "Hits recorded in the team sheet.", r: "Runs recorded in the team sheet.", rbi: "Runs batted in recorded in the team sheet.",
  hbp: "Hit-by-pitch outcomes recorded in the team sheet.",
  fb: "Fastball pitches recorded in the pitching sheet.", fb_k: "The pitching sheet’s fastball strike count; K here denotes strikes, not strikeouts.",
  ch: "Changeup pitches recorded in the pitching sheet.", ch_k: "The pitching sheet’s changeup strike count; K here denotes strikes, not strikeouts.",
  bb_pitch_family: "Breaking-ball pitches recorded in the pitching sheet. This BB field does not mean walks.",
  bb_pitch_family_k: "The pitching sheet’s breaking-ball strike count. This is separate from walks and strikeouts.",
};

export function statDefinition(metric: string): string {
  if(metric.startsWith("qpa_game_"))return statDefinition(metric.slice(9));
  const definition = PLAYER_METRICS.find(item => item.key === metric || item.label.toLowerCase() === metric.toLowerCase())
    ?? PLAYER_METRICS.find(item => item.units.some(unit => normalizePlayerMetric(metric, unit)?.key === item.key));
  return STAT_DEFINITIONS[definition?.key ?? metric.toLowerCase()] ?? "This is a recorded field from the source report or team sheet. Its scoring rules follow that source; a team-specific definition has not been confirmed yet.";
}
