import Link from "next/link";
import { Download, FileSpreadsheet, Upload } from "lucide-react";
import { requireAccess } from "@/lib/auth";
import { PageHeading } from "@/components/page-heading";
import { SubmitButton } from "@/components/submit-button";
import { stageImport } from "./actions";
import type { ImportDraft } from "@/lib/types";
const messages: Record<string,string> = { file: "Choose a nonempty .csv file no larger than 1 MiB.", season: "Enter a season as YYYY or YYYY-YY, such as 2026 or 2026-27.", stage: "Unable to create the preview. Check your access and database setup, then try again.", draft: "That import could not be found." };
export default async function ImportPage({ searchParams }: { searchParams: Promise<{ error?: string; validation?: string }> }) {
  const { supabase } = await requireAccess(["admin"]);
  const params = await searchParams;
  const { data, error } = await supabase.from("roster_imports").select("id,filename,season,status,created_at,preview").order("created_at",{ascending:false}).limit(12);
  if (error) throw new Error("Unable to load import history.");
  const history = (data ?? []) as Pick<ImportDraft,"id"|"filename"|"season"|"status"|"created_at"|"preview">[];
  return <><PageHeading section="Administration" title="Roster import" description="Upload your master roster, review the changes, then approve the batch."><a className="btn btn-secondary" href="/templates/master-roster.csv" download><Download size={16} />Download CSV template</a></PageHeading>
    {(params.error || params.validation) && <p role="alert" className="notice notice-error mb-6">{params.validation?.slice(0,400) || messages[params.error ?? ""] || "Unable to process this import."}</p>}
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="panel p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-50 text-pacu-red"><Upload size={20} /></span><div><h2 className="mb-0 text-lg font-semibold">Upload master roster</h2><p className="muted mb-0 text-xs">01 Upload · 02 Review · 03 Approve</p></div></div><form action={stageImport} className="space-y-6"><label>Season<input name="season" placeholder="2026 or 2026-27" pattern="20[0-9]{2}(-[0-9]{2})?" maxLength={7} required /></label><label>Roster CSV<input name="file" type="file" accept=".csv,text/csv" required /></label><p className="muted text-xs">Use the exact 16-column template. Up to 500 rows and 1 MiB per upload.</p><SubmitButton pendingText="Validating roster…">Validate and preview <FileSpreadsheet size={16} /></SubmitButton></form></section><aside className="panel p-7"><p className="eyebrow text-pacu-red">Before you upload</p><h2 className="mb-5 text-lg font-semibold">Keep identities consistent.</h2><ul className="list-disc space-y-4 pl-5 text-sm text-gray-600"><li>Match athletes using their permanent <strong>athlete_code</strong>.</li><li>Blank optional cells preserve existing values. Jersey number <strong>0</strong> is valid.</li><li>Every rejected row must be corrected before the batch can be approved.</li><li>Omitted athletes stay in the roster. Imports never create accounts or change account links.</li></ul></aside></div>
    <h2 className="mb-4 mt-8 text-lg font-bold">Recent imports</h2>{!history.length ? <div className="panel p-8 text-center text-sm text-gray-500">No imports yet. Your first validated upload will appear here.</div> : <div className="panel table-wrap"><table><thead><tr><th>File</th><th>Season</th><th>Status</th><th>Rows</th><th>Created (UTC)</th></tr></thead><tbody>{history.map(item => <tr key={item.id}><td><Link className="font-semibold text-pacu-red" href={`/admin/import/${item.id}`}>{item.filename}</Link></td><td>{item.season}</td><td><span className={`badge ${item.status === "applied" ? "badge-green" : ""}`}>{item.status}</span></td><td>{item.preview.rows.length}</td><td>{new Date(item.created_at).toISOString().slice(0,16).replace("T"," ")}</td></tr>)}</tbody></table></div>}</>;
}
